### ISSUE TITLE
okBuck does not work for a simple sample Android app

### ISSUE THREAD

**Issue by dsyang** [uber/okbuck#223]
I tried using this on Jake Warton's sample u2020 app https://github.com/JakeWharton/u2020 and okBuck doesn't generate any buck files. Here are the repro steps:

```
> git clone https://github.com/JakeWharton/u2020
> ./gradlew assemble
Add okBuck to the build.gradle file
> ./gradlew buckWrapper
> ./gradlew okBuck
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
:okbuckClean
:okbuck

BUILD SUCCESSFUL
> ./buckw targets
 NO PREVIOUS SUCCESSFUL OKBUCK RUN
 RUNNING OKBUCK...

Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
 DELETED OLD BUCK FILES
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
:okbuck

BUILD SUCCESSFUL

Total time: 1.25 secs

 PROCEEDING WITH BUCK

 BUCK NOT FOUND IN '/Users/dsyang/.gradle/caches/okbuck/buck'. INSTALLING BUCK...
Cloning into '/Users/dsyang/.gradle/caches/okbuck/buck'...
remote: Counting objects: 161119, done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 161119 (delta 26), reused 0 (delta 0), pack-reused 161043
Receiving objects: 100% (161119/161119), 425.25 MiB | 9.62 MiB/s, done.
Resolving deltas: 100% (98351/98351), done.
Checking connectivity... done.
Checking out files: 100% (9056/9056), done.
Buck does not appear to have been built -- building Buck!
All done, continuing with build.
Using watchman.
[+] PARSING BUCK FILES...0.4s
> git st
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   build.gradle

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.buckconfig
	.buckconfig.local
	.buckd/
	.okbuck/
	buck-out/
	buckw


> python --version    
Python 2.7.10
> ./gradlew okBuck   
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
:okbuckClean
:okbuck

BUILD SUCCESSFUL

Total time: 2.913 secs
> ./buckw targets    
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
[+] PARSING BUCK FILES...0.2s
>
```

**Comment by hzsweers** [comment]
Deferring to Gautam on this, but to be fair u2020 is not a simple project.

**Comment by kageiit** [comment]
If you want to use a simple test app for okbuck, you can use okbuck applied to wordpess maintained by the gradle folks

https://github.com/gradle/perf-android-medium

Or you can use the sample apps from this repo

as @hzsweers pointed out, u2020 is not a trivial app, but it should be able to work with okbuck with tweaks

**Comment by dsyang** [comment]
Sorry simple definitely wasn't the right word to use there. What I meant to say is "app of reasonable complexity"

I think having okBuck work out of the box for something like u2020 would go a long way to getting more people to adopt it.  

"It simply works with something as complex as u2020 and your app is less / as complex as that. It should not be a problem for you to adopt okBuck and enjoy lightning fast build times!" is a much better story to tell devs than "You'll need to tweak it"

**Comment by dsyang** [comment]
> it should be able to work with okbuck with tweaks 

@kageiit Any idea what tweaks I'd need to make? The error messages say very little. 
In fact, it looks like okBuck is completing successfully and not complaining at all, it's just not doing anything

**Comment by kageiit** [comment]
I will take a look at u2020. But the u2020 app it is not a good way to compare any app to it as complex/less complex. Every app is unique in its design. We have a much better story than u2020 because it is used by uber, lyft, airbnb and square internally on their large android codebases.

**Comment by kageiit** [comment]
If you want real complex android projects that are opensource and works with okbuck, you should take a look at 

- https://github.com/Piasy/AndroidTDDBootStrap
- https://github.com/kageiit/android-studio-gradle-test
