### ISSUE TITLE
buck install app not work

### ISSUE THREAD

**Issue by gcobc12677** [uber/okbuck#233]
when I run ```buck install app```, I get this message
```
[2016-11-09 20:53:13.465][error][command:da4ea383-875c-42c3-8a70-ef51aafb6d17][tid:57][com.facebook.buck.io.Watchman] Error 1 executing get-sockname
[2016-11-09 20:53:13.478][error][command:da4ea383-875c-42c3-8a70-ef51aafb6d17][tid:57][com.facebook.buck.apple.AppleToolchainDiscovery] Identifier, version not found for toolchain path /Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain, ignoring
[2016-11-09 20:53:13.478][error][command:da4ea383-875c-42c3-8a70-ef51aafb6d17][tid:57][com.facebook.buck.apple.AppleToolchainDiscovery] Identifier, version not found for toolchain path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain, ignoring
[2016-11-09 20:53:13.504][error][command:da4ea383-875c-42c3-8a70-ef51aafb6d17][tid:57][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.IllegalStateException: /usr/local/Cellar/android-ndk/r11c/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
        at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
        at com.facebook.buck.android.NdkCxxPlatforms.getToolPath(NdkCxxPlatforms.java:580)
        at com.facebook.buck.android.NdkCxxPlatforms.getCTool(NdkCxxPlatforms.java:629)
        at com.facebook.buck.android.NdkCxxPlatforms.build(NdkCxxPlatforms.java:373)
        at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:138)
        at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:105)
        at com.facebook.buck.rules.KnownBuildRuleTypes.createBuilder(KnownBuildRuleTypes.java:351)
        at com.facebook.buck.rules.KnownBuildRuleTypes.createInstance(KnownBuildRuleTypes.java:226)
        at com.facebook.buck.rules.KnownBuildRuleTypesFactory.create(KnownBuildRuleTypesFactory.java:49)
        at com.facebook.buck.rules.Cell.<init>(Cell.java:120)
        at com.facebook.buck.rules.Cell.createCell(Cell.java:182)
        at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:779)
        at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1467)
        at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1552)
        at com.facebook.buck.cli.Main.nailMain(Main.java:1665)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
```

but in my NDK location, I have ```arm-linux-androideabi-4.9```
is version cause this problem?
thanks for help

**Comment by gcobc12677** [comment]
and then I try to add the follow text to ```.buckconfig.local```
```
[ndk]
    gcc_version = 4.9
```

then I get this message when I retry ```buck install app```
```
[2016-11-09 21:18:55.174][error][command:e580a532-c68f-4ec4-95dc-c0cd826c0093][tid:175][com.facebook.buck.io.Watchman] Error 1 executing get-sockname
[2016-11-09 21:18:55.186][error][command:e580a532-c68f-4ec4-95dc-c0cd826c0093][tid:175][com.facebook.buck.apple.AppleToolchainDiscovery] Identifier, version not found for toolchain path /Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain, ignoring
[2016-11-09 21:18:55.186][error][command:e580a532-c68f-4ec4-95dc-c0cd826c0093][tid:175][com.facebook.buck.apple.AppleToolchainDiscovery] Identifier, version not found for toolchain path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain, ignoring
[+] PARSING BUCK FILES...0.1s
BUILD FAILED: //app:bin_release: parameter 'manifestEntries': cannot coerce '{placeholders={applicationId=com.rytass.geeyang.buckdemo}}' to class com.facebook.buck.rules.coercer.ManifestEntries, Unrecognized field "placeholders" (class com.facebook.buck.rules.coercer.ManifestEntries$Json), not marked as ignorable (5 known properties: "version_name", "version_code", "target_sdk_version", "min_sdk_version", "debug_mode"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.facebook.buck.rules.coercer.Json["placeholders"])

```

sorry for annoying

**Comment by kageiit** [comment]
I think you are using a very old version of buck

set your `.buckversion` file to point to latest buck master

**Comment by gcobc12677** [comment]
I have ```.buckversion``` in the root of my project
and the content is ```5083f81ad5c8f95fce3c46c24f13012c85a3d2c4``` that is the latest commit

what I did is add ```classpath 'com.uber:okbuck:0.9.3'``` and ```apply plugin: 'com.uber.okbuck'```
then run ```./gradlew :buckWrapper``` and ```./gradlew :okbuck```
after that I try to ```buck install app``` then I get the message mentioned above
do I miss some steps or I have a wrong concept?

**Comment by kageiit** [comment]
You dont need to run okbuck yourself

use `./buckw` instead of `buck` when running the build command

**Comment by gcobc12677** [comment]
I keep trying and install my project on my device successfully
Thanks for help
