### ISSUE TITLE
BUILD FAILED: //app:manifest_recordDebug failed on step generate_manifest with an exception: Error generating manifest file

### ISSUE THREAD

**Issue by changjiashuai** [uber/okbuck#256]
```
BUILD FAILED: //app:manifest_recordDebug failed on step generate_manifest with an exception:
Error generating manifest file
com.facebook.buck.util.HumanReadableException: Error generating manifest file
        at com.facebook.buck.android.GenerateManifestStep.execute(GenerateManifestStep.java:101)
        at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:54)
        at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1359)
        at com.facebook.buck.rules.CachingBuildEngine.lambda$10(CachingBuildEngine.java:340)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:77)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
        at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
        at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by hzsweers** [comment]
Could you give us more details? A sample project would be helpful, as there's not much we can infer from this trace alone.

**Comment by kageiit** [comment]
Need a sample project to understand whats going on

**Comment by aphexcx** [comment]
I've noticed this happening when there are _any_ messages from the manifest merger at all, even warnings. Check the previous lines before this message and try fixing the warnings/errors. To our discussion: I think that okbuck should ignore warnings from the merger and only halt on error.

**Comment by kageiit** [comment]
@aphexcx The failure is happening in buck and not okbuck from the stacktrace. The need to run the manifest merger as part of okbuck will be largely removed when https://github.com/facebook/buck/pull/1018 is merged

**Comment by Macarse** [comment]
@aphexcx  Fixing manifest merger warnings solved my problem. Thanks!

**Comment by kageiit** [comment]
Closing this as it is an upstream buck issue
