### ISSUE TITLE
Execution failed for task ':buildDepCache'

### ISSUE THREAD

**Issue by Piasy** [uber/okbuck#303]
``` java
* What went wrong:
Execution failed for task ':buildDepCache'.
> /Users/piasy/src/Yolo/piasyRepo/YOLO-Android/YOLO-Android-Client/model/build/intermediates/unmocked-androidmodel.jar

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildDepCache'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:233)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.nio.file.NoSuchFileException: /Users/piasy/src/Yolo/piasyRepo/YOLO-Android/YOLO-Android-Client/model/build/intermediates/unmocked-androidmodel.jar
        at com.uber.okbuck.core.dependency.DependencyCache$_build_closure5.doCall(DependencyCache.groovy:133)
        at com.uber.okbuck.core.dependency.DependencyCache.build(DependencyCache.groovy:128)
        at com.uber.okbuck.core.dependency.DependencyCache.<init>(DependencyCache.groovy:60)
        at com.uber.okbuck.OkBuckGradlePlugin$_apply_closure2$_closure8.doCall(OkBuckGradlePlugin.groovy:114)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:588)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:569)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 15 more


BUILD FAILED
```

When I run `./gradlew :buildDepCache`, no error happens, but when I run `./gradlew okbuck`, it fails, and if I touch such file, it succeeds. I'm using `v0.13.1`.

**Comment by kageiit** [comment]
Is `unmocked-androidmodel.jar` generated by some gradle task? What is it used for? This might be similar to sqldelight where you have to hook in something before okbuck task to generate any necessary files

**Comment by kageiit** [comment]
Have not heard back any info on this issue. Please comment back if you have more info to debug. Closing this ticket for now. Will re-open if needed
