### ISSUE TITLE
NullPointerException: Unknown platform type ARMV7

### ISSUE THREAD

**Issue by cesarferreira** [uber/okbuck#342]
Do you guys have any idea of why this is happening?

```bash
$ ./buckw build appDebug                                                        
[-] PROCESSING BUCK FILES...FINISHED 0.1s
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...0.0s
[2017-01-19 17:36:07.176][error][command:null][tid:59][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.NullPointerException: Unknown platform type ARMV7
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
	at com.facebook.buck.android.AndroidNativeLibsPackageableGraphEnhancer.enhance(AndroidNativeLibsPackageableGraphEnhancer.java:194)
	at com.facebook.buck.android.AndroidBinaryGraphEnhancer.createAdditionalBuildables(AndroidBinaryGraphEnhancer.java:223)
	at com.facebook.buck.android.AndroidBinaryDescription.createBuildRule(AndroidBinaryDescription.java:254)
	at com.facebook.buck.android.AndroidBinaryDescription.createBuildRule(AndroidBinaryDescription.java:1)
	at com.facebook.buck.rules.DefaultTargetNodeToBuildRuleTransformer.transform(DefaultTargetNodeToBuildRuleTransformer.java:46)
	at com.facebook.buck.rules.BuildRuleResolver.requireRule(BuildRuleResolver.java:136)
	at com.facebook.buck.rules.ActionGraphCache$1.visit(ActionGraphCache.java:152)
	at com.facebook.buck.rules.ActionGraphCache$1.visit(ActionGraphCache.java:1)
	at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:62)
	at com.facebook.buck.rules.ActionGraphCache.createActionGraph(ActionGraphCache.java:161)
	at com.facebook.buck.rules.ActionGraphCache.getActionGraph(ActionGraphCache.java:90)
	at com.facebook.buck.cli.BuildCommand.createActionGraphAndResolver(BuildCommand.java:607)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:383)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:339)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:198)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:91)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1257)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:700)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1937)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
```

**Comment by kageiit** [comment]
Make sure you install the latest ndk and set the Android ndk home variable. This is documented in the wiki

**Comment by cesarferreira** [comment]
You are right, thanks!

**Comment by LichFaker** [comment]
Got a similar issue, but I already set the Android ndk home variable(`ANDROID_NDK_HOME `)
```
[2017-08-07 10:57:30.277][error][command:null][tid:385][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.NullPointerException: Unknown platform type ARMV7
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
        at com.facebook.buck.android.AndroidNativeLibsPackageableGraphEnhancer.enhance(AndroidNativeLibsPackageableGraphEnhancer.java:198)
        at com.facebook.buck.android.AndroidBinaryGraphEnhancer.createAdditionalBuildables(AndroidBinaryGraphEnhancer.java:211)
        at com.facebook.buck.android.AndroidBinaryDescription.createBuildRule(AndroidBinaryDescription.java:265)
        at com.facebook.buck.android.AndroidBinaryDescription.createBuildRule(AndroidBinaryDescription.java:1)
        at com.facebook.buck.rules.DefaultTargetNodeToBuildRuleTransformer.transform(DefaultTargetNodeToBuildRuleTransformer.java:46)
        at com.facebook.buck.rules.BuildRuleResolver.requireRule(BuildRuleResolver.java:142)
        at com.facebook.buck.rules.ActionGraphCache$1.visit(ActionGraphCache.java:178)
        at com.facebook.buck.rules.ActionGraphCache$1.visit(ActionGraphCache.java:1)
        at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:36)
        at com.facebook.buck.rules.ActionGraphCache.createActionGraph(ActionGraphCache.java:184)
        at com.facebook.buck.rules.ActionGraphCache.getActionGraph(ActionGraphCache.java:114)
        at com.facebook.buck.cli.BuildCommand.createActionGraphAndResolver(BuildCommand.java:728)
        at com.facebook.buck.cli.BuildCommand.createGraphs(BuildCommand.java:436)
        at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:388)
        at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:357)
        at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:227)
        at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:69)
        at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:84)
        at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1348)
        at com.facebook.buck.cli.Main.runMainThenExit(Main.java:746)
        at com.facebook.buck.cli.Main.nailMain(Main.java:2141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)

```

**Comment by kageiit** [comment]
Did you try setting `ANDROID_NDK` ?

**Comment by LichFaker** [comment]
@kageiit  yes, also did not work

**Comment by donglua** [comment]
[ndk]
  cpu_abis = arm, armv7, x86

**Comment by kageiit** [comment]
What do you get if you run `ls $ANDROID_NDK`

**Comment by LichFaker** [comment]
Set `ANDROID_NDK ` is right. It's my fault. It's already set `ANDROID_NDK` in `.bashrc` by brew which is no longer exists.
thx any way

**Comment by lingz** [comment]
I'm seeing the same problem, ANDROID_NDK is set but cannot find the platform

**Comment by lingz** [comment]
The solution for me, was to unset all the ndk properties in .buckconfig, download NDK 13b and point only `ANDROID_NDK` there, and unset `ANDROID_NDK_REPOSITORY`
