### ISSUE TITLE
My debug build type fails with an OOM while dexing

### ISSUE THREAD

**Issue by Macarse** [uber/okbuck#384]
Any idea of what I can try?

This is what I see:
```
$ ./buckw build MyAppNormalDebug
[-] PROCESSING BUCK FILES...FINISHED 0.2s [100%]
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...2m 34.5s [98%] (261/264 JOBS, 261 UPDATED, 0 [0.0%] CACHE MISS)
 |=> //MyApp:src_normalDebug#dex...  53.6s (running dx[53.6s])
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
```

until I run out of memory and the stack is:

```
./buckw build MyAppNormalDebug
[2017-02-08 18:37:20.065][error][command:null][tid:35][com.facebook.buck.event.listener.SuperConsoleEventBusListener] Rendering exception
java.lang.OutOfMemoryError: Java heap space


[-] PROCESSING BUCK FILES...FINISHED 0.3s [100%] 🐳  New buck daemon
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...6m 35.0s [99%] (262/264 JOBS, 0 UPDATED, 0 [0.0%] CACHE MISS)
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
[2017-02-08 18:37:25.787][error][command:null][tid:25][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building //MyApp:src_normalDebug#dex failed. Caused by OutOfMemoryError: Java heap space
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:388)
	at com.facebook.buck.cli.BuildCommand.executeBuild(BuildCommand.java:803)
	at com.facebook.buck.cli.BuildCommand.executeLocalBuild(BuildCommand.java:750)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:465)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:394)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:360)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:212)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:91)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1292)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:712)
	at com.facebook.buck.cli.Main.nailMain(Main.java:2078)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Building //MyApp:src_normalDebug#dex failed. Caused by OutOfMemoryError: Java heap space
	at com.facebook.buck.command.Build.executeBuild(Build.java:292)
	at com.facebook.buck.command.Build.executeAndPrintFailuresToEventBus(Build.java:344)
	... 15 more
Caused by: java.lang.RuntimeException: Building //MyApp:src_normalDebug#dex failed. Caused by OutOfMemoryError: Java heap space
	at com.facebook.buck.rules.CachingBuildEngine.maybeAttachBuildRuleNameToException(CachingBuildEngine.java:1053)
	at com.facebook.buck.rules.CachingBuildEngine.access$6(CachingBuildEngine.java:1035)
	at com.facebook.buck.rules.CachingBuildEngine$4.onFailure(CachingBuildEngine.java:1022)
	at com.facebook.buck.util.concurrent.MoreFutures$1.onFailure(MoreFutures.java:140)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1764)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:634)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1405)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$2(WeightedListeningExecutorService.java:109)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:81)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by kageiit** [comment]
You can increase the max heap size in https://buckbuild.com/concept/buckjavaargs.html

**Comment by Macarse** [comment]
@kageiit I don't think it has anything to do with the available memory. The task keeps dexing for 6 mins where gradle full clean build takes 3 mins.

**Comment by kageiit** [comment]
Hmm, its hard to say without knowing what the dx task is trying to do but you can try to set this option in your root build.gradle

https://github.com/uber/okbuck/blob/ebcea6f0950d37536e18e0bfe7ae6eb39ebf4064/Usage.md#L45

**Comment by Macarse** [comment]
@kageiit yep, that was my doubt as well, there is no way to get a log of what buck is executing?

**Comment by Macarse** [comment]
I am running the build again but I am not sure if what I added is correct.

On the root build.gradle:

```
apply plugin: 'com.uber.okbuck'

okbuck {
  extraBuckOpts = [
    'MyAppNormalDebug': [
      "binary": ["trim_resource_ids = True"]
    ]
  ]
}
```

and I build with `./buckw build MyAppNormalDebug`

**Comment by Macarse** [comment]
Nope, same thing :(

**Comment by Macarse** [comment]
mmm inside `buck-out/log/buck-0.log` there is a command which look like this:

```
/Users/myUser/.gradle/caches/okbuck/buck/third-party/java/dx/etc/dx --dex --no-optimize --force-jumbo --output /Users/myUser/Documents/myRepo/buck-out/gen/MyApp/src_normalDebug#dex.dex.jar /Users/myUser/Documents/myRepo/buck-out/gen/MyApp/lib__src_normalDebug__output/src_normalDebug.jar
```

Running that on my command like I also get something similar:
```
UNEXPECTED TOP-LEVEL ERROR:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.google.common.collect.MapMakerInternalMap$EntryFactory$1.newEntry(MapMakerInternalMap.java:358)
	at com.google.common.collect.MapMakerInternalMap$EntryFactory.copyEntry(MapMakerInternalMap.java:505)
	at com.google.common.collect.MapMakerInternalMap$Segment.copyEntry(MapMakerInternalMap.java:2158)
	at com.google.common.collect.MapMakerInternalMap$Segment.expand(MapMakerInternalMap.java:2630)
	at com.google.common.collect.MapMakerInternalMap$Segment.put(MapMakerInternalMap.java:2511)
	at com.google.common.collect.MapMakerInternalMap.putIfAbsent(MapMakerInternalMap.java:3524)
	at com.android.dx.rop.type.Type.putIntern(Type.java:864)
	at com.android.dx.rop.type.Type.getArrayType(Type.java:793)
	at com.android.dx.rop.type.Type.intern(Type.java:325)
	at com.android.dx.rop.type.Type.internReturnType(Type.java:396)
	at com.android.dx.rop.type.Prototype.intern(Prototype.java:108)
	at com.android.dx.rop.cst.CstBaseMethodRef.<init>(CstBaseMethodRef.java:50)
	at com.android.dx.rop.cst.CstMethodRef.<init>(CstMethodRef.java:31)
	at com.android.dx.cf.cst.ConstantPoolParser.parse0(ConstantPoolParser.java:310)
	at com.android.dx.cf.cst.ConstantPoolParser.parse(ConstantPoolParser.java:150)
	at com.android.dx.cf.cst.ConstantPoolParser.parseIfNecessary(ConstantPoolParser.java:124)
	at com.android.dx.cf.cst.ConstantPoolParser.getPool(ConstantPoolParser.java:115)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:482)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.parseClass(Main.java:792)
	at com.android.dx.command.dexer.Main.access$1600(Main.java:91)
	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1727)
	at com.android.dx.command.dexer.Main.processClass(Main.java:778)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:746)
	at com.android.dx.command.dexer.Main.access$1200(Main.java:91)
	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1688)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:700)
```

**Comment by kageiit** [comment]
Hmm seems like buck is dexing out of memory. This should be followed up as an upstream issue on buck at this point.

Also, the key name is 'android_binary'. Not 'binary'

**Comment by Macarse** [comment]
I wonder how I could miss that since I am copy pasting...

**Comment by Macarse** [comment]
@kageiit Adding more heap fixed the problem. I ended up adding `-Xmx4g` to my `.buckjavaargs`.

Is okBuck reading the `javaMaxHeapSize` from the android section on gradle files to set the heap size?
In my particular case I needed more than the amount specify in gradle file but it might help others.
