### ISSUE TITLE
Excluded module is being referenced in the cache

### ISSUE THREAD

**Issue by cwoodwar6** [uber/okbuck#395]
Repro project: https://github.com/cwoodwar6/okbuck-test-project

Failure:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':setupOkbuck'.
> /Users/cwoodward/Development/okbuck-test-project/.okbuck/cache/okbuck-test-project.app-library-release.aar
```

But I exclude `app-library`:
```
okbuck {
   Set<Project> projects = new HashSet<>();
   for (Project module : project.subprojects) {
     if (module.getName().equals("app-library")) {
       continue;
     }
     projects.add(module);
   }
   buckProjects = projects;
 }
```

It shouldn't look at any project I've excluded. This is only an issue if I've run a `./gradlew clean` and haven't rebuilt using Gradle.  But I'd very much like to not have Buck builds depend on Gradle.

Full stacktrace:

```
Caused by: java.nio.file.FileAlreadyExistsException: /Users/cwoodward/Development/okbuck-test-project/.okbuck/cache/okbuck-test-project.app-library-release.aar
        at com.uber.okbuck.core.dependency.DependencyCache$_build_closure5.doCall(DependencyCache.groovy:135)
        at com.uber.okbuck.core.dependency.DependencyCache.build(DependencyCache.groovy:130)
        at com.uber.okbuck.core.dependency.DependencyCache.<init>(DependencyCache.groovy:61)
        at com.uber.okbuck.OkBuckGradlePlugin$_apply_closure1$_closure8.doCall(OkBuckGradlePlugin.groovy:121)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:596)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:577)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
```

**Comment by kageiit** [comment]
I do not think this would work. `app` depends on `app-library`. okbuck'ing sub projects only makes sense for projects that are isolated from others. If you have cross project dependencies, there is no possible way to do okbuck for just a subset of them
