### ISSUE TITLE
Mockito does not work with Android-related classes

### ISSUE THREAD

**Issue by konmik** [uber/okbuck#410]
1. `git clone https://github.com/uber/okbuck.git`
2. Go to `app/src/main/java/com.uber.okbuck.ExampleUnitTest`
3. add `        Context context = mock(Context.class);
        doReturn("Today").when(context).getString(R.string.android_asst_date_format_today);
` into `testAdd()` method
4. run `./buckw test //app:test_devDebug`

```
FAILURE com.uber.okbuck.ExampleUnitTest testAdd: Stub!
java.lang.RuntimeException: Stub!
        at android.content.Context.getString(Context.java:30)
        at com.uber.okbuck.ExampleUnitTest.testAdd(ExampleUnitTest.java:24)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at com.facebook.buck.testrunner.SameThreadFailOnTimeout.lambda$new$0(SameThreadFailOnTimeout.java:44)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by runningcode** [comment]
Seeing this as well.

**Comment by cwoodwar6** [comment]
Running with Robolectric is the suggested fix, but to better understand the issue and provide an alternative solution, I'll explain what is happening.

Gradle will create a “mockable android” jar that it uses to run unit tests against. This mockable version of the android jar will [strip out final qualifiers, stub exceptions, etc](https://android.googlesource.com/platform/tools/base/+/studio-1.1-dev/build-system/builder/src/main/java/com/android/builder/testing/MockableJarGenerator.java). This allows Mockito to mock these Android classes such as Context.

Buck expects you to either run full java unit tests or to run with Robolectric if you need to access Android classes. If you prefer to mimic the behavior of Gradle instead of running your tests with Robolectric, you can copy the mockable android jar that Gradle creates and set it as a test dependency.

**Comment by kageiit** [comment]
Going to close this given the available workarounds
