### ISSUE TITLE
error: Error: String types not allowed (at 'versionCode' with value 'null')

### ISSUE THREAD

**Issue by AllenAWKing** [uber/okbuck#440]
Got an error when I was running "./buckw build appRelease":
__buck-out/bin/app/__manifest_bin_release#aapt_package__/AndroidManifest.xml:2: error: Error: String types not allowed (at 'versionCode' with value 'null').__

However, works fine for "versionName"...

**Comment by ChaitanyaPramod** [comment]
versionCode is of integer type

**Comment by kageiit** [comment]
Please use an integer for versionCode as suggested

**Comment by AllenAWKing** [comment]
@kageiit @ChaitanyaPramod Thanks for your comments~

Please let me describe this again:
In "[PROJECT_PATH]/app/src/main/AndroidManifest.xml", I wrote versionCode like this:
<....versionCode="20" ..../>
After I ran "./buckw build appRelease", in "[PROJECT_PATH]/app/src/main/AndroidManifest.xml", versionCode came to <...versionCode="null".../>

I don't know if there is a known issue, please help to have a look, thanks you all in advance.

Allen.A.W

**Comment by AllenAWKing** [comment]
More comments: 
I don't know why versionCode="null" in generated AndroidManifest.xml, could you guys kind to have a look? Thanks~  @kageiit @ChaitanyaPramod 

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.cootek.smartinputv5.sticker.keyboard_sticker_dummy"
    android:versionCode="null"
    android:versionName="20" >

**Comment by kageiit** [comment]
did you set `versionCode` in `defaultConfig` in your build.gradle file?

What does your gradle file look like?

**Comment by AllenAWKing** [comment]
@kageiit Thank you very much for your help!  
After I added versionCode in defaultConfig, I got another issue:

Could you please have me to have a look if there is anything wrong...

_**[tid:163][com.facebook.buck.event.listener.LoggingBuildListener] Error when creating APK at: buck-out/gen/app/bin_release.signed.apk.
java.security.UnrecoverableKeyException: Cannot recover key**_

## app/build.gradle:
....
    signingConfigs {
	release {
		keyAlias 'keyalias'
		storeFile file('app.keystore')
		storePassword 'keystore password'
	}
    }
    defaultConfig {
        applicationId "com.okbuck.demo"
        minSdkVersion 15
        targetSdkVersion 22
	versionCode 20
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    buildTypes {
        release {
            minifyEnabled false
	    signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
....

## Trace:
[2017-05-10 14:25:31.117][debug][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:164][com.facebook.buck.json.ProjectBuildFileParser] Started process com.facebook.buck.util.ProcessExecutor$LaunchedProcessImpl@22f10ce4 successfully
[2017-05-10 14:25:31.205][debug][command:null][tid:175][com.facebook.buck.json.ProjectBuildFileParser] Closing buck.py process stdin
[2017-05-10 14:25:31.205][debug][command:null][tid:175][com.facebook.buck.json.ProjectBuildFileParser] Closing buck.py process stdin
[2017-05-10 14:25:31.205][debug][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:147][com.facebook.buck.rules.ActionGraphCache] Computing TargetGraph HashCode...
[2017-05-10 14:25:31.206][info ][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:147][com.facebook.buck.rules.ActionGraphCache] ActionGraph cache miss. Cache was empty.
[2017-05-10 14:25:31.211][debug][command:null][tid:175][com.facebook.buck.json.ProjectBuildFileParser] Waiting for process com.facebook.buck.util.ProcessExecutor$LaunchedProcessImpl@22f10ce4 to exit...
[2017-05-10 14:25:31.211][debug][command:null][tid:175][com.facebook.buck.json.ProjectBuildFileParser] Waiting for process com.facebook.buck.util.ProcessExecutor$LaunchedProcessImpl@22f10ce4 to exit...
[2017-05-10 14:25:31.211][debug][command:null][tid:175][com.facebook.buck.json.ProjectBuildFileParser] Process com.facebook.buck.util.ProcessExecutor$LaunchedProcessImpl@22f10ce4 exited cleanly.
[2017-05-10 14:25:31.211][debug][command:null][tid:175][com.facebook.buck.json.ProjectBuildFileParser] Process com.facebook.buck.util.ProcessExecutor$LaunchedProcessImpl@22f10ce4 exited cleanly.
[2017-05-10 14:25:31.216][info ][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:147][com.facebook.buck.rules.ActionGraphCache] ActionGraph cache assignment. skipActionGraphCache? false
[2017-05-10 14:25:31.217][debug][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:147][com.facebook.buck.cli.MetadataChecker] Checking metadata_storage for /opt/data/cootekime/workspace/sticker_android/StickerPackGenertor/DummyStickerPack
[2017-05-10 14:25:31.246][debug][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:176][com.facebook.buck.rules.CachingBuildEngine] Cache miss for '//app:bin_release' with rulekey 'ac7bcb00936a0ab8327b00cb1ae7454081c21eb3'
[2017-05-10 14:25:31.332][debug][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:177][com.facebook.buck.rules.CachingBuildEngine] Fetched '//.okbuck/gen/app/release:app.keystore' from cache with rulekey '00b1f732cf6f71fcbcf57798c9f325dc184ff4d7'
[2017-05-10 14:25:31.334][warn ][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:174][com.facebook.buck.rules.DefaultOnDiskBuildInfo] DefaultOnDiskBuildInfo.getHash(primary_dex_hash): Hash not found
[2017-05-10 14:25:31.345][debug][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:168][com.facebook.buck.rules.CachingBuildEngine] Building locally: //app:bin_release
[2017-05-10 14:25:31.347][warn ][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:163][com.facebook.buck.event.listener.LoggingBuildListener] Error when creating APK at: buck-out/gen/app/bin_release.signed.apk.
java.security.UnrecoverableKeyException: Cannot recover key
java.security.UnrecoverableKeyException: Cannot recover key
	at sun.security.provider.KeyProtector.recover(KeyProtector.java:328)
	at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:146)
	at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:96)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(JavaKeyStore.java:70)
	at java.security.KeyStore.getKey(KeyStore.java:1023)
	at com.facebook.buck.android.ApkBuilderStep.createKeystoreProperties(ApkBuilderStep.java:183)
	at com.facebook.buck.android.ApkBuilderStep.execute(ApkBuilderStep.java:121)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1512)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$18(CachingBuildEngine.java:356)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[2017-05-10 14:25:31.348][debug][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:147][com.facebook.buck.command.Build] Got an exception during the build.
com.facebook.buck.step.StepFailedException: //app:bin_release failed with exit code 1:
apk_builder
	at com.facebook.buck.step.StepFailedException.createForFailingStepWithExitCode(StepFailedException.java:62)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:54)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1512)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$18(CachingBuildEngine.java:356)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[2017-05-10 14:25:31.348][warn ][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:163][com.facebook.buck.event.listener.LoggingBuildListener] BUILD FAILED: //app:bin_release failed with exit code 1:
apk_builder
[2017-05-10 14:25:31.352][info ][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:163][com.facebook.buck.event.listener.LoggingBuildListener] Build finished at 2017-05-10 14:25:31.348
[2017-05-10 14:25:31.353][info ][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:147][com.facebook.buck.cli.Main] Awaiting termination of HTTP Write executor service. Waiting for all jobs to complete, or up to maximum of 1800 seconds...
[2017-05-10 14:25:31.353][info ][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:147][com.facebook.buck.cli.Main] Awaiting termination of CounterAggregatorExecutor executor service. Waiting for all jobs to complete, or up to maximum of 20 seconds...
[2017-05-10 14:25:31.354][debug][command:24e47289-17c9-44d9-bfb4-49071f276477][tid:158][com.facebook.buck.util.perf.ProcessTracker] shutDown
[2017-05-10 14:25:31.354][debug][command:null][tid:157][com.google.common.util.concurrent.ServiceManager] Service PerfStatsTracking [TERMINATED] has terminated. Previous state was: STOPPING

**Comment by kageiit** [comment]
Seems like your keystore config is incorrect. Check with the keystore config in the samples in this repo. Your password/alias may not be right.

**Comment by AllenAWKing** [comment]
@kageiit Thanks! I changed storefile to absolute path and it works!

BTW, is there any way to build an release apk unsigned?

**Comment by kageiit** [comment]
buck does not support building apk without a keystore. If you feel thats needed, you should open a task on the buck issue tracker

**Comment by AllenAWKing** [comment]
@kageiit Okay, Thanks very much for all your help!
