### ISSUE TITLE
ValueError: No JSON object could be decoded ater running any command

### ISSUE THREAD

**Issue by yashasvigirdhar** [uber/okbuck#442]
I get this error after running  any command on the command line from the buck wrapper. An example would be  

`./buckw targets`

```
./buckw: line 61: 12127 Trace/BPT trap: 5       watchman watch-project $WORKING_DIR > /dev/null 2>&1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`
```

Python version : 2.7.10
okbuck version : 0.20.7

This error however doesn't seem to affect what ever I am doing. I can build my app successfully. 
But just curious about this error.

**Comment by kageiit** [comment]
Might be your watchman is broken. Try to reinstall it

**Comment by yashasvigirdhar** [comment]
Yeah, it's gone after reinstalling watchman.

Thanks !
