### ISSUE TITLE
Dependency versions need to be scoped by configuration

### ISSUE THREAD

**Issue by felipecsl** [uber/okbuck#443]
This has surfaced for us while upgrading to Dagger 2.10 or newer. Since now dagger-compiler depends on Guava 21, which requires Java 8, that version ends up leaking into the `compile` dependencies if your app ever depends on Guava, even if it's an older version.
In order to reproduce this bug with OkBuck, just add `compile 'com.google.guava:guava:19.0'` to `app/build.gradle` and run `./buckw build app:bin_prodDebug`
You'll see:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
	at com.android.dx.command.dexer.Main.processClass(Main.java:780)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:746)
	at com.android.dx.command.dexer.Main.access$1200(Main.java:91)
	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1688)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:700)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:597)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:324)
	at com.android.dx.command.dexer.Main.run(Main.java:295)
	at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:212)
	at com.facebook.buck.android.DxStep.execute(DxStep.java:187)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:47)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1538)
	at com.facebook.buck.rules.CachingBuildEngine.lambda$17(CachingBuildEngine.java:354)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:81)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:476)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.parseClass(Main.java:792)
	at com.android.dx.command.dexer.Main.access$1600(Main.java:91)
	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1727)
	at com.android.dx.command.dexer.Main.processClass(Main.java:778)
	... 23 more
1 error; aborting

BUILD FAILED: //.okbuck/cache:com.google.guava.guava-21.0.jar#dex failed with exit code 1:
```

, which is caused by having `'//.okbuck/cache:com.google.guava.guava-21.0.jar'` in the `deps` list of `apps:src_prodDebug` in `app/BUCK`.

As a workaround, you can use `resolutionStrategy.force 'com.google.guava:guava:19.0'`

**Comment by felipecsl** [comment]
To further show how this is not the correct behavior, running; 
```
./gradlew app:dependencyInsight --configuration compile --dependency guava
```

gives us:

```
:app:dependencyInsight
com.google.guava:guava:19.0
\--- compile
```

**Comment by kageiit** [comment]
Single highest version of any dependency is by design.

This is likely not going to be fixed to keep logic simpler in okbuck. The correct way to get around issues like this is to use Extra dep caches as detailed in https://github.com/uber/okbuck/pull/411

Then use `DEFS` to replace the problematic dependency with the version from the extra deps cache
