### ISSUE TITLE
PluginApplicationException: Failed to apply plugin [id 'com.uber.okbuck']

### ISSUE THREAD

**Issue by vanniktech** [uber/okbuck#453]
I'm getting `PluginApplicationException: Failed to apply plugin [id 'com.uber.okbuck']` after upgrading from `0.20.7` to `0.21.0`. I'm running 2.3.1 & Gradle 3.5.

> Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'com.uber.okbuck']
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:155)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:44)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
        at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
        at build_4pf8dpmxf3726vll2ppm0drzh.run(/Users/nik/tmp/coyo-messenger-android/build.gradle:11)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 61 more
Caused by: org.gradle.internal.reflect.ObjectInstantiationException: Could not create an instance of type com.uber.okbuck.extension.LintExtension_Decorated.
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:44)
        at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
        at org.gradle.api.internal.plugins.DefaultConvention.create(DefaultConvention.java:103)
        at com.uber.okbuck.OkBuckGradlePlugin.apply(OkBuckGradlePlugin.groovy:85)
        at com.uber.okbuck.OkBuckGradlePlugin.apply(OkBuckGradlePlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139)
        ... 71 more
Caused by: java.lang.NoSuchMethodError: org.gradle.api.artifacts.ResolvableDependencies.getArtifacts()Lorg/gradle/api/artifacts/ArtifactCollection;
        at com.uber.okbuck.core.util.ProjectUtil.findVersionInClasspath(ProjectUtil.java:70)
        at com.uber.okbuck.core.util.LintUtil.getDefaultLintVersion(LintUtil.java:32)
        at com.uber.okbuck.extension.LintExtension.<init>(LintExtension.java:28)
        at com.uber.okbuck.extension.LintExtension_Decorated.<init>(Unknown Source)
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:42)
        ... 78 more

**Comment by kageiit** [comment]
@vanniktech Is this still a problem with v0.22.1?

**Comment by kageiit** [comment]
Can you also try with Gradle 4.0 now that it is out?

**Comment by vanniktech** [comment]
Nope, all working now. Thanks :)
