### ISSUE TITLE
App not able to run in emulator although installed successfully.

### ISSUE THREAD

**Issue by himgupta** [uber/okbuck#492]
Hello,

When I am running the command ./buckw install appDebug command on my project .Following logs are coming and app is getting installed on the emulator but launcher activity is not opening neither I am able to launch app by clicking on it.
Logs :
~/workspace/table$ ./buckw install appDebug
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
cat: /home/himanshugupta/workspace/table/.buckversion: No such file or directory
Installing apk on emulator-5554 (Nexus_7kitkat).
Successfully ran install apk //app:bin_debug on 1 device(s)
[-] PARSING BUCK FILES...FINISHED 0.2s [100%]
[-] PROCESSING BUCK FILES...FINISHED 0.3s [100%] 🐳  New buck daemon
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.3s [100%] (2/2 JOBS, 0 UPDATED, 0 [0.0%] CACHE MISS)
[-] INSTALLING...FINISHED 1.3s

Is that due to buckversion file not present ? How to create this file as I have tried by cleaning the projecct also but the file is not generated.I used command ./buckw clean

**Comment by cwoodwar6** [comment]
From the logs you've posted it looks like the APK was successfully installed on the device. Could you run with the `-r` flag to see if it launches? (`./buckw install -r appDebug`). 

Could you also post the logcat from the device when the APK is launched? Sounds like an issue with the APK.

**Comment by kageiit** [comment]
the buckversion file is not related. Try using the `-r` flag as @cwoodwar6 pointed out.

**Comment by kageiit** [comment]
Closing due to inactivity
