### ISSUE TITLE
Support for Android Gradle Plugin 3.x

### ISSUE THREAD

**Issue by jbarr21** [uber/okbuck#502]
Running `buck build appDevDebug` on the okbuck sample app with Android Gradle Plugin 3.0.0-beta1 yields the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > com.android.build.gradle.api.BaseVariant.getOutputs()Ljava/util/List;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

 OKBUCK FAILED
```

**Comment by artem-zinnatullin** [comment]
Maybe this will be helpful: Bugsnag Gradle Plugin also needed to fix that https://github.com/bugsnag/bugsnag-android-gradle-plugin/pull/46

**Comment by kageiit** [comment]
Okbuck does not use the `getOutputs` api anymore.

I am waiting to move okbuck fully to a template engine before doing the migration to 3.x

**Comment by artem-zinnatullin** [comment]
Ohh, that's couple days then, kool kool

**Comment by artem-zinnatullin** [comment]
Just update, with OkBuck 0.28.5, AGP 3.0.0-beta5, Gradle 4.1 we're getting following errors in all modules during `buckw project`:

```console
Execution failed for task ':module:okbuck'.
> Resolving configuration 'debugCompile' directly is not allowed

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':module:okbuck'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalStateException: Resolving configuration 'debugCompile' directly is not allowed
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.assertResolvingAllowed(DefaultConfiguration.java:888)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:434)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1600(DefaultConfiguration.java:114)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies.getResolutionResult(DefaultConfiguration.java:1026)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies_Decorated.getResolutionResult(Unknown Source)
        at org.gradle.plugins.ide.internal.resolver.DefaultIdeDependencyResolver.getIncomingResolutionResult(DefaultIdeDependencyResolver.java:210)
        at org.gradle.plugins.ide.internal.resolver.DefaultIdeDependencyResolver.getIdeRepoFileDependencies(DefaultIdeDependencyResolver.java:117)
        at org.gradle.plugins.ide.internal.IdeDependenciesExtractor.resolvedExternalDependencies(IdeDependenciesExtractor.java:181)
        at org.gradle.plugins.ide.internal.IdeDependenciesExtractor.extractRepoFileDependencies(IdeDependenciesExtractor.java:77)
        at org.gradle.plugins.ide.internal.IdeDependenciesExtractor$extractRepoFileDependencies.call(Unknown Source)
        at com.uber.okbuck.core.dependency.DependencyUtils.downloadSourceJars(DependencyUtils.groovy:45)
        at com.uber.okbuck.core.dependency.DependencyUtils$downloadSourceJars$1.call(Unknown Source)
        at com.uber.okbuck.core.model.base.Scope.extractConfigurations(Scope.groovy:121)
        at com.uber.okbuck.core.model.base.Scope.<init>(Scope.groovy:57)
        at com.uber.okbuck.core.model.base.Scope$_from_closure3.doCall(Scope.groovy:71)
        at com.sun.proxy.$Proxy100.apply(Unknown Source)
        at com.uber.okbuck.core.model.base.Scope.from(Scope.groovy:68)
        at com.uber.okbuck.core.model.base.Scope.from(Scope.groovy:65)
        at com.uber.okbuck.core.model.base.Scope$from$2.call(Unknown Source)
        at com.uber.okbuck.core.model.android.AndroidTarget.getMain(AndroidTarget.groovy:123)
        at com.uber.okbuck.core.model.base.Target.getProperty(Target.groovy)
        at com.uber.okbuck.composer.android.AndroidResourceRuleComposer.compose(AndroidResourceRuleComposer.groovy:18)
        at com.uber.okbuck.composer.android.AndroidResourceRuleComposer$compose$3.call(Unknown Source)
        at com.uber.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.groovy:158)
        at com.uber.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.groovy:144)
        at com.uber.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.groovy:205)
        at com.uber.okbuck.generator.BuckFileGenerator$_createRules_closure1.doCall(BuckFileGenerator.groovy:83)
        at com.uber.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.groovy:64)
        at com.uber.okbuck.generator.BuckFileGenerator.generate(BuckFileGenerator.groovy:49)
        at com.uber.okbuck.generator.BuckFileGenerator$generate$6.call(Unknown Source)
        at com.uber.okbuck.OkBuckGradlePlugin$_apply_closure2$_closure9$_closure13.doCall(OkBuckGradlePlugin.groovy:186)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:681)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:656)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more


* Get more help at https://help.gradle.org

BUILD FAILED in 6s
2 actionable tasks: 2 executed

OKBUCK FAILED 
```

And here is list of same issues (and PRs that fixed them) from other projects:

- https://github.com/jeremylong/dependency-check-gradle/issues/31 PR https://github.com/jeremylong/dependency-check-gradle/pull/33
- https://github.com/google/protobuf-gradle-plugin/pull/121 - PR https://github.com/google/protobuf-gradle-plugin/pull/121
- https://github.com/johndevs/gradle-vaadin-plugin/issues/331 Commit https://github.com/johndevs/gradle-vaadin-plugin/commit/a337a5782d44171e5da1abfc8a50ee2e4f2d3b4c

**Comment by artem-zinnatullin** [comment]
Diving deeper, I've made couple changes to OkBuck to ignore configurations that are not `isCanBeResolved()` and converted our project so it builds with Gradle and AGP 3.0.0-beta6 (just released). 

But now I'm getting following error during `buckw project`:

```console
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':module:okbuck'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all artifacts for configuration ':module:compile'.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:882)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1500(DefaultConfiguration.java:114)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationArtifactCollection.ensureResolved(DefaultConfiguration.java:1217)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationArtifactCollection.getArtifacts(DefaultConfiguration.java:1189)
        at com.uber.okbuck.core.model.base.Scope$_extractConfigurations_closure13.doCall(Scope.groovy:129)
        at com.uber.okbuck.core.model.base.Scope.extractConfigurations(Scope.groovy:128)
        at com.uber.okbuck.core.model.base.Scope.<init>(Scope.groovy:57)
        at com.uber.okbuck.core.model.base.Scope$_from_closure3.doCall(Scope.groovy:71)
        at com.sun.proxy.$Proxy100.apply(Unknown Source)
        at com.uber.okbuck.core.model.base.Scope.from(Scope.groovy:68)
        at com.uber.okbuck.core.model.base.Scope.from(Scope.groovy:65)
        at com.uber.okbuck.core.model.base.Scope$from$0.call(Unknown Source)
        at com.uber.okbuck.core.model.android.AndroidTarget.getMain(AndroidTarget.groovy:123)
        at com.uber.okbuck.core.model.base.Target.getProperty(Target.groovy)
        at com.uber.okbuck.composer.android.AndroidResourceRuleComposer.compose(AndroidResourceRuleComposer.groovy:18)
        at com.uber.okbuck.composer.android.AndroidResourceRuleComposer$compose.call(Unknown Source)
        at com.uber.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.groovy:158)
        at com.uber.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.groovy:144)
        at com.uber.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.groovy:205)
        at com.uber.okbuck.generator.BuckFileGenerator$_createRules_closure1.doCall(BuckFileGenerator.groovy:83)
        at com.uber.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.groovy:64)
        at com.uber.okbuck.generator.BuckFileGenerator.generate(BuckFileGenerator.groovy:49)
        at com.uber.okbuck.generator.BuckFileGenerator$generate.call(Unknown Source)
        at com.uber.okbuck.OkBuckGradlePlugin$_apply_closure2$_closure9$_closure13.doCall(OkBuckGradlePlugin.groovy:186)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:681)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:656)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve project :anothermodule.
Required by:
    project :module
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$EdgeState.calculateTargetConfigurations(DependencyGraphBuilder.java:457)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$EdgeState.attachToTargetConfigurations(DependencyGraphBuilder.java:417)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.attachToTargetRevisionsSerially(DependencyGraphBuilder.java:223)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolveEdges(DependencyGraphBuilder.java:213)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:148)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:121)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:86)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:138)
        at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:73)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:66)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$4.run(DefaultConfiguration.java:469)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:461)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:437)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1600(DefaultConfiguration.java:114)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies.getResolutionResult(DefaultConfiguration.java:1026)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies_Decorated.getResolutionResult(Unknown Source)
        at org.gradle.plugins.ide.internal.resolver.DefaultIdeDependencyResolver.getIncomingResolutionResult(DefaultIdeDependencyResolver.java:210)
        at org.gradle.plugins.ide.internal.resolver.DefaultIdeDependencyResolver.getIdeRepoFileDependencies(DefaultIdeDependencyResolver.java:117)
        at org.gradle.plugins.ide.internal.IdeDependenciesExtractor.resolvedExternalDependencies(IdeDependenciesExtractor.java:181)
        at org.gradle.plugins.ide.internal.IdeDependenciesExtractor.extractRepoFileDependencies(IdeDependenciesExtractor.java:77)
        at org.gradle.plugins.ide.internal.IdeDependenciesExtractor$extractRepoFileDependencies.call(Unknown Source)
        at com.uber.okbuck.core.dependency.DependencyUtils.downloadSourceJars(DependencyUtils.groovy:47)
        at com.uber.okbuck.core.dependency.DependencyUtils$downloadSourceJars$2.call(Unknown Source)
        at com.uber.okbuck.core.model.base.Scope.extractConfigurations(Scope.groovy:123)
        ... 54 more
Caused by: org.gradle.api.internal.attributes.AttributeMatchException: Could not select value from candidates [release] using AlternateDisambiguationRule.BuildTypeRule.
        at org.gradle.api.internal.attributes.DefaultDisambiguationRuleChain$InstantiatingAction.execute(DefaultDisambiguationRuleChain.java:92)
        at org.gradle.api.internal.attributes.DefaultDisambiguationRuleChain$InstantiatingAction.execute(DefaultDisambiguationRuleChain.java:75)
        at org.gradle.api.internal.attributes.DefaultDisambiguationRuleChain.execute(DefaultDisambiguationRuleChain.java:68)
        at org.gradle.api.internal.attributes.DefaultDisambiguationRuleChain.execute(DefaultDisambiguationRuleChain.java:32)
        at org.gradle.api.internal.attributes.DefaultAttributesSchema$MergedSchema.disambiguate(DefaultAttributesSchema.java:167)
        at org.gradle.internal.component.model.ComponentAttributeMatcher$Matcher.disambiguate(ComponentAttributeMatcher.java:234)
        at org.gradle.internal.component.model.ComponentAttributeMatcher$Matcher.selectClosestMatches(ComponentAttributeMatcher.java:211)
        at org.gradle.internal.component.model.ComponentAttributeMatcher$Matcher.getMatches(ComponentAttributeMatcher.java:165)
        at org.gradle.internal.component.model.ComponentAttributeMatcher.match(ComponentAttributeMatcher.java:89)
        at org.gradle.api.internal.attributes.DefaultAttributesSchema$DefaultAttributeMatcher.matches(DefaultAttributesSchema.java:148)
        at org.gradle.internal.component.model.LocalComponentDependencyMetadata.selectConfigurations(LocalComponentDependencyMetadata.java:116)
        at org.gradle.internal.component.local.model.DslOriginDependencyMetadataWrapper.selectConfigurations(DslOriginDependencyMetadataWrapper.java:65)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$EdgeState.calculateTargetConfigurations(DependencyGraphBuilder.java:454)
        ... 81 more
Caused by: java.lang.NullPointerException
        at com.android.build.gradle.internal.dependency.AlternateDisambiguationRule.execute(AlternateDisambiguationRule.java:46)
        at com.android.build.gradle.internal.dependency.AlternateDisambiguationRule$BuildTypeRule.execute(AlternateDisambiguationRule.java:84)
        at org.gradle.api.internal.attributes.DefaultDisambiguationRuleChain$InstantiatingAction.execute(DefaultDisambiguationRuleChain.java:90)
        ... 93 more


* Get more help at https://help.gradle.org

BUILD FAILED in 5s
2 actionable tasks: 2 executed

OKBUCK FAILED 
```

My guess is that OkBuck will need to support/mimic AGP behavior related to new flavor/buildType matching behavior across modules, see https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#resolve_matching_errors

I had to apply `matchingFallbacks = ['release']` for `debug` build type in all app modules, that works for Gradle build, but doesn't work with OkBuck.

**Comment by seanabraham** [comment]
Any updates on this @kageiit / @jbarr21 / @artem-zinnatullin 

OkBuck has now moved to a templating engine as far as I understand

**Comment by kageiit** [comment]
Im currently finish up D8 support in buck. I will look at this next week

**Comment by krishnaChaitanyaAripaka** [comment]
Hi,
I tried integrating okbuck in my app with following configurations and I have observed strange behaviour with okbuck. It does not work for the below configuration

Failure :  Gradle 4.1, Android Plugin 3.0.0-beta6, okbuck (from 0.24.0)

Success : Gradle 4.1, Android Plugin 2.3.3,  okbuck (all versions)
Success : Gradle 4.1, Android Plugin 3.0.0-beta6,  okbuck (till 0.23.3)


* What went wrong:
Execution failed for task ':app:okbuck'.
> Resolving configuration 'debugCompile' directly is not allowed

**Comment by felipecsl** [comment]
@kageiit friendly ping on this now that 3.0 stable is out :)
I could possibly look into this if you're too busy

**Comment by kageiit** [comment]
I have a branch I can push up. But the main thing that has me hesitating is that we need acces to some internal apis that will become public in 3.1 . It will be a breaking change from 3.0 to 3.1 as well in terms of okbuck compatibility.

Also, making the next version of okbuck backwards compatible with 2.3 will be very hard so I am going to just break compatibility and only support 3.x from next release. Trying to make sure there are no other bugs before I do that

**Comment by felipecsl** [comment]
re: no backwards compatibility - sounds good to me. thanks for the update!

**Comment by artem-zinnatullin** [comment]
@kageiit branch would be great! Even if it's incomplete :)

**Comment by kageiit** [comment]
Pushed changes up to https://github.com/uber/okbuck/tree/agp_3_x_wip . There is a bunch to do still regarding getting project dependencies to work correctly using some internal APIs in AGP

**Comment by kassim** [comment]
is it in a useable state yet? (even if beta)
was really looking forward to trying out Okbuck

**Comment by kageiit** [comment]
See #568 and use `0.33.0-alpha01` till we are able to merge the PR

**Comment by kageiit** [comment]
https://github.com/uber/okbuck/releases/tag/v0.33.0 is out with support for 3.x

**Comment by hi-dhl** [comment]
for AndroidStudio 3.0+,  mainMoudle has buildTypes and buildTypes as same as libModule  buildTypes and buildTypes  ,it would like:

mainModule

    buildTypes {
        release {
            buildConfigField "boolean", "LOG_DEBUG", "false"
            zipAlignEnabled true
            shrinkResources true
            minifyEnabled true
            proguardFiles 'proguard-rules.pro'
        }

        debug {
            buildConfigField "boolean", "LOG_DEBUG", "true"
            zipAlignEnabled true
            shrinkResources false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug2{

        }
    }

libModule:

    buildTypes {
        release {

        }

        debug {

        }

        debug2{

        }
    }

or you can use matchingFallbacks solve this [click][1]


  [1]: https://developer.android.google.cn/studio/build/gradle-plugin-3-0-0-migration
