### ISSUE TITLE
Travis is failing.

### ISSUE THREAD

**Issue by runningcode** [uber/okbuck#569]
Travis is failing while running instrumentation tests
`./buckw test //app:instrumentation_demoDebug_test`
Running this locally fails with this exception:
```
01-10 17:20:36.254 3086-3086/com.uber.okbuck.example.demo.debug E/AndroidRuntime: FATAL EXCEPTION: main
          Process: com.uber.okbuck.example.demo.debug, PID: 3086
   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.uber.okbuck.example.demo.debug/com.uber.okbuck.example.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f070058
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
    at android.app.ActivityThread.access$800(ActivityThread.java:135)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5017)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
    at dalvik.system.NativeStart.main(Native Method)
 Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f070058
    at android.content.res.Resources.loadDrawable(Resources.java:2101)
    at android.content.res.Resources.getDrawable(Resources.java:700)
    at android.support.v7.widget.VectorEnabledTintResources.superGetDrawable(VectorEnabledTintResources.java:74)
    at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:433)
    at android.support.v7.widget.VectorEnabledTintResources.getDrawable(VectorEnabledTintResources.java:67)
    at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:360)
    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:198)
    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
    at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:753)
    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
    at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:85)
    at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:128)
    at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:149)
    at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:29)
    at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:54)
    at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:202)
    at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:183)
    at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
    at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:70)
    at com.uber.okbuck.example.MainActivity.onCreate(MainActivity.java:66)
    at android.app.Activity.performCreate(Activity.java:5231)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:532)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
    at android.app.ActivityThread.access$800(ActivityThread.java:135) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:136) 
    at android.app.ActivityThread.main(ActivityThread.java:5017) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:515) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
    at dalvik.system.NativeStart.main(Native Method) 
 Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #0: invalid drawable tag vector
    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
    at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
    at android.content.res.Resources.loadDrawable(Resources.java:2097)
    at android.content.res.Resources.getDrawable(Resources.java:700) 
    at android.support.v7.widget.VectorEnabledTintResources.superGetDrawable(VectorEnabledTintResources.java:74) 
    at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:433) 
    at android.support.v7.widget.VectorEnabledTintResources.getDrawable(VectorEnabledTintResources.java:67) 
    at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:360) 
    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:198) 
    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186) 
    at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:753) 
    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191) 
    at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:85) 
    at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:128) 
    at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:149) 
    at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:29) 
    at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:54) 
    at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:202) 
    at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:183) 
    at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519) 
    at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:70) 
    at com.uber.okbuck.example.MainActivity.onCreate(MainActivity.java:66) 
    at android.app.Activity.performCreate(Activity.java:5231) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
    at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:532) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
    at android.app.ActivityThread.access$800(ActivityThread.java:135) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:136) 
    at android.app.ActivityThread.main(ActivityThread.java:5017) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:515) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
    at dalvik.system.NativeStart.main(Native Method) 
```
Some googling around leads me to believe that this is related to support vector drawables?

**Comment by runningcode** [comment]
cc @raviagarwal7 @kageiit

**Comment by raviagarwal7** [comment]
the test works locally for me with this change - https://github.com/uber/okbuck/pull/568
Travis is failing to start an emulator so disabled the test for now.

```
╰─$ ./buckw test //app:instrumentation_demoDebug_test                                                                                                                                                  1 ↵
Action graph will be rebuilt because files have been added or removed.
Building: finished in 0.2 sec (100%) 180/180 jobs, 0 updated, 0.0% cache miss
  Total time: 0.2 sec
Testing: finished in 11.9 sec (3 PASS/0 FAIL)
RESULTS FOR //app:instrumentation_demoDebug_test //app:test_demoDebug
PASS      1.0s  2 Passed   0 Skipped   0 Failed   com.uber.okbuck.example.test.MainActivityTest (emulator-5554)
PASS     155ms  1 Passed   0 Skipped   0 Failed   com.uber.okbuck.ExampleUnitTest
TESTS PASSED
```

**Comment by runningcode** [comment]
Where do you see travis failing to start an emulator? I see this last build before the test was disabled as having the same failure I noted above: https://travis-ci.org/uber/okbuck/builds/327359986

**Comment by raviagarwal7** [comment]
my bad, you are right I thought this to be the failure
```
The command "android-wait-for-emulator" exited with 127.
3.03s$ adb shell input keyevent 82
```

I was able to run the test successfully locally though, not sure what's up with the Travis CI.

Also, if you look at this run where the test run was disabled - https://travis-ci.org/uber/okbuck/builds/327376362
It seems like the build failed due to 
```
The command "android-wait-for-emulator" exited with 127.
3.31s$ adb shell input keyevent 82

Done. Your build exited with 1.
```

**Comment by runningcode** [comment]
the `android-wait-for-emulator` script is only available on travis android instances i.e. set `language: android` instead of `language: android`

**Comment by runningcode** [comment]
You can recreate the failure if you use an emulator/device with SDK 19 just like travis.
