### ISSUE TITLE
Issue with Okbuck and proguard configuration.

### ISSUE THREAD

**Issue by runningcode** [uber/okbuck#572]
When I run okbuck, it fails for me with the following stacktrace:
```
Caused by: com.fizzed.rocker.RenderingException: com/uber/okbuck/template/android/AndroidBinaryRule.rocker.raw [line 57:24]: com/uber/okbuck/template/base/BuckRule.rocker.raw [line 4:1]: NullPointerException in render
        at com.fizzed.rocker.runtime.DefaultRockerTemplate.__render(DefaultRockerTemplate.java:105)
        at com.fizzed.rocker.runtime.DefaultRockerModel.doRender(DefaultRockerModel.java:67)
        at com.fizzed.rocker.runtime.DefaultRockerModel.render(DefaultRockerModel.java:42)
        at com.uber.okbuck.template.core.Rule.render(Rule.java:81)
        at com.uber.okbuck.template.core.Rule$render$11.call(Unknown Source)
        at com.uber.okbuck.template.core.Rule$render$11.call(Unknown Source)
        at com.uber.okbuck.generator.BuckFileGenerator.generate(BuckFileGenerator.groovy:50)
        at com.uber.okbuck.generator.BuckFileGenerator$generate.call(Unknown Source)
        at com.uber.okbuck.OkBuckGradlePlugin$_apply_closure2$_closure9$_closure12.doCall(OkBuckGradlePlugin.groovy:181)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:718)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:691)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 30 more
Caused by: com.fizzed.rocker.RenderingException: com/uber/okbuck/template/base/BuckRule.rocker.raw [line 4:1]: NullPointerException in render
        at com.fizzed.rocker.runtime.DefaultRockerTemplate.__render(DefaultRockerTemplate.java:105)
        at com.fizzed.rocker.runtime.DefaultRockerModel.doRender(DefaultRockerModel.java:67)
        at com.fizzed.rocker.runtime.DefaultRockerTemplate$Internal.renderValue(DefaultRockerTemplate.java:261)
        at com.uber.okbuck.template.android.AndroidBinaryRule$Template.__doRender(AndroidBinaryRule.java:351)
        at com.fizzed.rocker.runtime.DefaultRockerTemplate.__render(DefaultRockerTemplate.java:98)
        ... 47 more
Caused by: java.lang.NullPointerException
        at com.fizzed.rocker.runtime.OutputStreamOutput.w(OutputStreamOutput.java:50)
        at com.fizzed.rocker.runtime.OutputStreamOutput.w(OutputStreamOutput.java:30)
        at com.fizzed.rocker.runtime.DefaultRockerTemplate$Internal.renderValue(DefaultRockerTemplate.java:282)
        at com.uber.okbuck.template.android.AndroidBinaryRule$Template.lambda$__doRender$5(AndroidBinaryRule.java:519)
        at com.fizzed.rocker.runtime.DefaultRockerTemplate$Internal.renderValue(DefaultRockerTemplate.java:257)
        at com.uber.okbuck.template.base.BuckRule$Template.__doRender(BuckRule.java:112)
        at com.fizzed.rocker.runtime.DefaultRockerTemplate.__render(DefaultRockerTemplate.java:98)
        ... 51 more
```

Looking at `AndroidBinaryRule.java:519` I saw 
```
__internal.renderValue(proguardConfig, false);
```
so i changed my app's release proguard configuration from `buildTypes.release.minifyEnable true` to `buildTypes.release.minifyEnable false` and it worked. :)

Not sure what the proper fix is here. cc @kageiit

**Comment by kageiit** [comment]
if you are enabling minify, okbuck expects you have a proguard configuration as well. Have you tried setting one?

**Comment by runningcode** [comment]
yeah, its set
```
buildTypes {
        release { // live
            debuggable false
            minifyEnabled true
            multiDexEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
}
```

**Comment by runningcode** [comment]
could it be an issue with `getDefaultProguardFile`?

**Comment by kageiit** [comment]
It's recommended to not use the defaults. See the okbuck samples. The getDefault could also be returning null in your code

**Comment by kageiit** [comment]
Closing since we appear to have found a workaround. Please comment if there is anything else related and I can re-open

**Comment by runningcode** [comment]
I'm going to try to make a PR to give this a better error message when the build fails with this error.
Maybe something like
`IllegalArgumentException("Make sure a proguard configuration exists and do not use getDefaultProguardFile")`?

**Comment by kassim** [comment]
for the sake of getting it running, removing the `proguardFiles` and `minifyEnabled` entries solved it for me - its probably as suggested above, that `getDefaultProguardFile` was returning null
