### ISSUE TITLE
'buck targets' failing with error 

### ISSUE THREAD

**Issue by preetb123** [uber/okbuck#580]
Getting following error while `./buckw targets`
I am using version `0.33.0-alpha01`
```
$ ./buckw targets
[2018-01-27 20:07:39.706][error][command:null][tid:14][com.facebook.buck.cli.Main] Uncaught exception at top level
com.google.common.util.concurrent.ExecutionError: java.lang.AssertionError: /Users/preetam/Library/Android/sdk/ndk-bundle/platforms/android-9/arch-arm doesn't exist.
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2216)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146)
        at com.facebook.buck.rules.AbstractKnownBuildRuleTypesProvider.get(AbstractKnownBuildRuleTypesProvider.java:67)
        at com.facebook.buck.rules.KnownBuildRuleTypesProvider.get(KnownBuildRuleTypesProvider.java:1)
        at com.facebook.buck.parser.PerBuildState.getAllTargetNodesJob(PerBuildState.java:181)
        at com.facebook.buck.parser.Parser.resolveTargetSpecs(Parser.java:512)
        at com.facebook.buck.parser.Parser.buildTargetGraphForTargetNodeSpecs(Parser.java:395)
        at com.facebook.buck.cli.TargetsCommand.buildTargetGraphAndTargets(TargetsCommand.java:602)
        at com.facebook.buck.cli.TargetsCommand.runWithExecutor(TargetsCommand.java:399)
        at com.facebook.buck.cli.TargetsCommand.runWithoutHelp(TargetsCommand.java:371)
        at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:232)
        at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:79)
        at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:82)
        at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1048)
        at com.facebook.buck.cli.Main.runMainThenExit(Main.java:393)
        at com.facebook.buck.cli.Main.nailMain(Main.java:1882)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:329)
Caused by: java.lang.AssertionError: /Users/preetam/Library/Android/sdk/ndk-bundle/platforms/android-9/arch-arm doesn't exist.
        at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)
        at com.facebook.buck.android.NdkCxxPlatforms$NdkCxxToolchainPaths.processPathPattern(NdkCxxPlatforms.java:956)
        at com.facebook.buck.android.NdkCxxPlatforms$NdkCxxToolchainPaths.processPathPattern(NdkCxxPlatforms.java:969)
        at com.facebook.buck.android.NdkCxxPlatforms$NdkCxxToolchainPaths.getSysroot(NdkCxxPlatforms.java:989)
        at com.facebook.buck.android.NdkCxxPlatforms.getCommonIncludes(NdkCxxPlatforms.java:750)
        at com.facebook.buck.android.NdkCxxPlatforms.getCPreprocessorFlags(NdkCxxPlatforms.java:778)
        at com.facebook.buck.android.NdkCxxPlatforms.build(NdkCxxPlatforms.java:484)
        at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:291)
        at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:256)
        at com.facebook.buck.android.NdkCxxPlatforms.getPlatforms(NdkCxxPlatforms.java:233)
        at com.facebook.buck.android.toolchain.impl.NdkCxxPlatformsProviderFactory.getNdkCxxPlatforms(NdkCxxPlatformsProviderFactory.java:64)
        at com.facebook.buck.android.toolchain.impl.NdkCxxPlatformsProviderFactory.createToolchain(NdkCxxPlatformsProviderFactory.java:43)
        at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.createToolchain(DefaultToolchainProvider.java:185)
        at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getOrCreate(DefaultToolchainProvider.java:169)
        at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getByName(DefaultToolchainProvider.java:134)
        at com.facebook.buck.toolchain.BaseToolchainProvider.getByName(BaseToolchainProvider.java:24)
        at com.facebook.buck.cxx.toolchain.CxxPlatformsProviderFactory.createToolchain(CxxPlatformsProviderFactory.java:46)
        at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.createToolchain(DefaultToolchainProvider.java:185)
        at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getOrCreate(DefaultToolchainProvider.java:169)
        at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getByName(DefaultToolchainProvider.java:134)
        at com.facebook.buck.toolchain.BaseToolchainProvider.getByName(BaseToolchainProvider.java:24)
        at com.facebook.buck.rules.AbstractKnownBuildRuleTypes.createInstance(AbstractKnownBuildRuleTypes.java:233)
        at com.facebook.buck.rules.AbstractDefaultKnownBuildRuleTypesFactory.create(AbstractDefaultKnownBuildRuleTypesFactory.java:42)
        at com.facebook.buck.rules.DefaultKnownBuildRuleTypesFactory.create(DefaultKnownBuildRuleTypesFactory.java:1)
        at com.facebook.buck.rules.AbstractKnownBuildRuleTypesProvider$1.load(AbstractKnownBuildRuleTypesProvider.java:46)
        at com.facebook.buck.rules.AbstractKnownBuildRuleTypesProvider$1.load(AbstractKnownBuildRuleTypesProvider.java:1)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
        ... 23 more
```

**Comment by runningcode** [comment]
this looks like an upstream bug. https://github.com/facebook/buck/issues/1684 
try using a newer version of buck?

**Comment by goindevs** [comment]
@runningcode I just tried with `brew install --HEAD buck` but getting same error.

**Comment by preetb123** [comment]
I installed buck with `brew install --HEAD buck` but was getting same error with `$./buckw targets`

Got it running with `$buck targets`.

Now getting following error while running `buck build appDebug`
```
$ buck build appDebug
Error parsing resources to generate resource IDs for Pair(//app:res_debug#resources-symlink-tree, buck-out/gen/app/res_debug#resources-symlink-tree/res).
com.facebook.buck.android.aapt.MiniAapt.ResourceParseException: Invalid definition of a resource: '@{user.firstName != null ? user.firstName + ` ` + user.lastName : `Add your name here`}'
com.facebook.buck.android.aapt.MiniAapt$ResourceParseException: Invalid definition of a resource: '@{user.firstName != null ? user.firstName + ` ` + user.lastName : `Add your name here`}'
        at com.facebook.buck.android.aapt.MiniAapt.processXmlFile(MiniAapt.java:533)
        at com.facebook.buck.android.aapt.MiniAapt.processXmlFilesForIds(MiniAapt.java:503)
        at com.facebook.buck.android.aapt.MiniAapt.execute(MiniAapt.java:185)
        at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
        at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.executeCommandsNowThatDepsAreBuilt(CachingBuildRuleBuilder.java:1809)
        at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.run(CachingBuildRuleBuilder.java:1762)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$2(WeightedListeningExecutorService.java:104)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$0(WeightedListeningExecutorService.java:78)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:206)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:195)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:115)
        at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:999)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Build failed: Command failed with exit code 1.
    When running <generate_resource_ids>.
    When building rule //app:res_debug.
```

is `data-binding` still not supported?

**Comment by preetb123** [comment]
I removed `data-binding` completely from my project, but i am still getting the above error on 
`buck build appDebug`. 
Tried `./gradlew clean` & `buck clean` Also removed the directory `buck-out` but still getting the above error.

Also, even after installing the latest buck(`version b08c8889ccdf18de641ee1fd12340fe817a453e9`) i get `android-9/arch-arm doesn't exist` error while doing `./buckw targets`

**Comment by preetb123** [comment]
I am able to get rid of all the previous errors by using `buck build appDebug` after cleaning the cache and using snapshot version of Butterknife and using Butterknife Gradle Plugin as given https://github.com/uber/okbuck/wiki/Known-caveats#butterknife. 
But now i am getting following errors with the code generated by https://github.com/apollographql/apollo-android

```shell
$ buck build appDebug
Build failed: Command failed with exit code 1.

~/workspace/sample_app/app/src/main/java/co/sampleapp/HomeActivity.java:810: error: package SampleQuery does not exist
  private void showSampleData(List<SampleQuery.AvailableData> availableData) {
                                                                 ^
~/workspace/sample_app/app/src/main/java/co/sampleapp/data/DetailsPollingEvent.java:3: error: cannot find symbol
import co.sampleapp.SampleQuery;
              ^
  symbol:   class SampleQuery
  location: package co.sampleapp
.
.
.
Errors: 26. Warnings: 1.

    When running <javac>.
    When building rule //app:src_debug.
```
Is there anything i can do to make this work?

**Comment by preetb123** [comment]
Fixed the above issue(temporarily and built the project successfully) by manually adding the path to the generated code in the `BUCK` file
```
android_library(
    name = 'src_debug',
    srcs = glob([
        'build/generated/source/apollo/co/sampleapp/**/*.java',
        'src/main/graphql/**/*.java',
        'src/main/java/**/*.java',
    ]),
    source = '8',
    target = '8',
```
But this needs to be done for other build configurations as well. 
I have added path to `sourceSets` as well, but it is not reflected in the `BUCK` file after `build`
```
sourceSets {
    main {
      java.srcDirs = [
          'src/main/java',
          'src/main/graphql',
          'build/generated/source/apollo/co/goin',
      ]
    }
  }
```

**Comment by kageiit** [comment]
@preetb123 you need to make the okbuck task depend on the apollo gradle plgin task. Okbuck has an example for sqldelight here: https://github.com/uber/okbuck/blob/master/build.gradle#L100

You should hookup something like this for apollo as well so that generated sourcesets are ported over to the BUCK files automatically

**Comment by preetb123** [comment]
Added following code
```
android {
  ...
  applicationVariants.all {
    Task okBuckTask = project.tasks.getByName("okbuck")
    Task apolloAndroidTask = project.tasks.getByName("generate${it.name.capitalize()}ApolloClasses")
    okBuckTask.dependsOn(apolloAndroidTask)
    project.android.sourceSets."${it.name}".java.srcDirs += [apolloAndroidTask.outputs.files[0] as String]
  }
}
```
But the glob field in the BUCK file not updated. Anything else needs to be done?

**Comment by kageiit** [comment]
@preetb123 See https://github.com/apollographql/apollo-android/issues/474 for your issue specifically :)

**Comment by preetb123** [comment]
I was able to get the BUCK file updated by adding `build/generated/source/apollo/co/sampleapp` to the `sourceSets` and with following commands
```
buck clean && buckw clean
rm -rf buck-out/ .okbuck/
./gradlew :buckWrapper
./buckw targets
buck targets
```

**Comment by kageiit** [comment]
You dont have to invoke `buck` directly. Always prefer to use the wrapper

**Comment by preetb123** [comment]
`./buckw targets` still gives me error
```
[2018-01-27 20:07:39.706][error][command:null][tid:14][com.facebook.buck.cli.Main] Uncaught exception at top level
com.google.common.util.concurrent.ExecutionError: java.lang.AssertionError: /Users/preetam/Library/Android/sdk/ndk-bundle/platforms/android-9/arch-arm doesn't exist.
       ...
Caused by: java.lang.AssertionError: /Users/preetam/Library/Android/sdk/ndk-bundle/platforms/android-9/arch-arm doesn't exist.
```
So, i had to use it just to make it work.

**Comment by kageiit** [comment]
What is the output of `./buckw --version`?

what version of okbuck are you using?

**Comment by preetb123** [comment]
I am using `okbuck` version `0.33.0-alpha01` 
```
$ ./buckw --version
CHANGES DETECTED IN:
app/build/apollo-codegen/node_modules/apollo-codegen/lib/javascript/flow/__tests__/helpers.js.map
app/build/apollo-codegen/node_modules/apollo-codegen/lib/javascript/flow/__tests__/codeGeneration.js.map
app/build/apollo-codegen/node_modules/apollo-codegen/lib/javascript/typescript/__tests__/helpers.js.map
app/build/apollo-codegen/node_modules/apollo-codegen/lib/javascript/typescript/__tests__/codeGeneration.js.map
app/build/apollo-codegen/node_modules/apollo-codegen/node_modules/source-map/dist/source-map.min.js.map
app/build/apollo-codegen/node_modules/apollo-codegen/lib/compiler/visitors/inlineRedundantTypeConditions.js.map
app/build/apollo-codegen/node_modules/apollo-codegen/lib/compiler/visitors/collectAndMergeFields.js.map
app/build/apollo-codegen/node_modules/apollo-codegen/lib/compiler/visitors/generateOperationId.js.map
app/build/apollo-codegen/node_modules/apollo-codegen/lib/compiler/visitors/typeCase.js.map
app/build/apollo-codegen/node_modules/apollo-codegen/lib/compiler/visitors/collectFragmentsReferenced.js.map
...and 77 more

RUNNING OKBUCK...

Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details
Parallel execution with configuration on demand is an incubating feature.
Build cache is an incubating feature.

> Task :okbuck 
Please do not use changing dependencies. They can cause hard to reproduce builds.
com.jakewharton.butterknife-9.0.0-SNAPSHOT.aar
com.apollographql.apollo.apollo-api-0.4.4-SNAPSHOT.jar
com.jakewharton.butterknife-annotations-9.0.0-SNAPSHOT.jar
com.apollographql.apollo.apollo-android-support-0.4.4-SNAPSHOT.aar
com.jakewharton.butterknife-compiler-9.0.0-SNAPSHOT.jar
com.apollographql.apollo.apollo-rx2-support-0.4.4-SNAPSHOT.jar
com.apollographql.apollo.apollo-runtime-0.4.4-SNAPSHOT.jar


BUILD SUCCESSFUL in 37s
4 actionable tasks: 4 executed

PROCEEDING WITH BUCK

buck version b08c8889ccdf18de641ee1fd12340fe817a453e9
$ ./buckw --version
buck version b08c8889ccdf18de641ee1fd12340fe817a453e9
```

**Comment by runningcode** [comment]
that version of buck is from nov 2017 and doesn't have the fix which was made in december 2017
https://github.com/facebook/buck/commit/c463548565e9cc831f7455a77b5b6612f95d71c0

**Comment by preetb123** [comment]
to get the latest version, i followed https://buckbuild.com/setup/getting_started.html
```
brew update
brew tap facebook/fb
brew install --HEAD buck
```

**Comment by runningcode** [comment]
don't use buck directly, use the buck wrapper. set your `.buckversion` file in the root repository to a newer version like `c463548565e9cc831f7455a77b5b6612f95d71c0`

**Comment by kageiit** [comment]
@preetb123 if you use `0.33.0-alpha03`, all these issues should go away as we fixed several of them in upstream buck. Let me know how that goes.

Once you upgrade, please run `./gradlew :buckWrapper` (only required once)

**Comment by kageiit** [comment]
@preetb123 there can be multiple apps in one repo, so its best if you configure your build tools and target as explained in the example - https://github.com/uber/okbuck/wiki/OkBuck-options-and-examples

**Comment by preetb123** [comment]
Everything worked nicely after setting the version to `0.33.0-alpha03` and `okbuck` config in root project's `build.gradle` to 
```
okbuck {
  buildToolVersion = '27.0.1'
  target = 'android-26'
  lint {
    disabled = true
  }
}
```
thanks again @kageiit
