### ISSUE TITLE
OkBuck sample app doesn't build

### ISSUE THREAD

**Issue by jbarr21** [uber/okbuck#599]
Steps:
```
git checkout master
git clean -fdx && watchman watch-del-all && killall java && rm -rf ~/.gradle/caches
./buckw build //app/...
```

Error:
```
WARNING: Output when parsing /Users/jbarr/Uber/okbuck/app/BUCK:
| Traceback (most recent call last):
|   File "/Users/jbarr/Uber/okbuck/.buckd/tmp/buck_run.hs3t98/buck_python_program8829352474705337913/__main__.py", line 10, in <module>
|     from buck_parser import buck
|   File "/Users/jbarr/Uber/okbuck/.buckd/resources/3062547759b7b98dcb312d5b57375c8610773d76/buck_server/buck_parser/buck.py", line 6, in <module>
| ModuleNotFoundError: No module named '__builtin__'
Parsing buck files: finished in 1.0 sec
BUILD FAILED: Buck wasn't able to parse /Users/jbarr/Uber/okbuck/app/BUCK:
No content to map due to end-of-input
 at [Source: com.google.common.io.CountingInputStream@2a8ceb83; line: 1, column: 0]
```

**Comment by jbarr21** [comment]
was just some issue with my python environment

**Comment by jbarr21** [comment]
Ensure you are using python 2.7
