### ISSUE TITLE
groovy.lang.MissingPropertyException: No such property: ANNOTATION_PROCESSOR_CONFIGURATION_NAME

### ISSUE THREAD

**Issue by galex** [uber/okbuck#600]
Hello,

There seems to be an issue with the Java Gradle Plugin on okbuck 0.34.1 (with Android Gradle Plugin **3.0.1** and Gradle **4.4**).

After setting a clean and new Android Project (module **app**) and adding a new Java Library in a module named **lib** which **app** depends on and running `./buckw targets`:
```
RUNNING OKBUCK...


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib:okbuck'.
> No such property: ANNOTATION_PROCESSOR_CONFIGURATION_NAME for class: org.gradle.api.plugins.JavaPlugin
```

Here is the stack trace:
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':lib:okbuck'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: groovy.lang.MissingPropertyException: No such property: ANNOTATION_PROCESSOR_CONFIGURATION_NAME for class: org.gradle.api.plugins.JavaPlugin
        at com.uber.okbuck.core.model.java.JavaTarget.getApt(JavaTarget.groovy:23)
        at com.uber.okbuck.core.model.base.Target.getProperty(Target.groovy)
        at com.uber.okbuck.composer.java.JavaLibraryRuleComposer.compose(JavaLibraryRuleComposer.groovy:25)
        at com.uber.okbuck.composer.java.JavaLibraryRuleComposer.compose(JavaLibraryRuleComposer.groovy)
        at com.uber.okbuck.composer.java.JavaLibraryRuleComposer$compose.call(Unknown Source)
        at com.uber.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.groovy:102)
        at com.uber.okbuck.generator.BuckFileGenerator$_createRules_closure1.doCall(BuckFileGenerator.groovy:64)
        at com.uber.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.groovy:61)
        at com.uber.okbuck.generator.BuckFileGenerator.generate(BuckFileGenerator.groovy:45)
        at com.uber.okbuck.generator.BuckFileGenerator$generate.call(Unknown Source)
        at com.uber.okbuck.OkBuckGradlePlugin$_apply_closure2$_closure11$_closure15.doCall(OkBuckGradlePlugin.groovy:198)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:718)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:691)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more
```
The Java module **lib** is set up as following:
```
apply plugin: 'java-library'

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

sourceCompatibility = "1.7"
targetCompatibility = "1.7"
```
Thank you in advance for your help!

**Comment by galex** [comment]
Tried, and sadly I got the same result with Android Gradle Plugin **3.1.0-rc02** and **3.2.0-alpha05** as well.

**Comment by kageiit** [comment]
oh right. Please use gradle 4.6 or above as well :)

**Comment by galex** [comment]
Thanks, using Gradle 4.6 does solves the issue!
