### ISSUE TITLE
Compilation failed to complete: Cannot fit requested classes in a single dex file 

### ISSUE THREAD

**Issue by galex** [uber/okbuck#602]
Hello,

For an Android Project where the minSDK is **21** and only `multiDexEnabled = true` is needed following the [android documentation](https://developer.android.com/studio/build/multidex.html), this is the error I get: 
```
com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:76)
        at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
        at com.android.tools.r8.D8.run(D8.java:67)
        at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:277)
        at com.facebook.buck.android.DxStep.execute(DxStep.java:236)
        at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
        at com.facebook.buck.android.SmartDexingStep.lambda$null$1(SmartDexingStep.java:232)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:127)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.utils.AbortException
        at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:77)
        at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:67)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:62)
        ... 12 more
        Suppressed: com.android.tools.r8.errors.DexOverflowException: Cannot fit requested classes in a single dex file (# fields: 73771 > 65536)
                at com.android.tools.r8.dex.VirtualFile.throwIfFull(VirtualFile.java:182)
                at com.android.tools.r8.dex.VirtualFile$MonoDexDistributor.run(VirtualFile.java:395)
                at com.android.tools.r8.dex.ApplicationWriter.distribute(ApplicationWriter.java:144)
                at com.android.tools.r8.dex.ApplicationWriter.write(ApplicationWriter.java:164)
                at com.android.tools.r8.D8.run(D8.java:167)
                at com.android.tools.r8.D8.lambda$run$0(D8.java:71)
                at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:58)
                ... 12 more
```

Thank you in advance for your help!
Alex

**Comment by runningcode** [comment]
In buck, each module must be smaller than 1 dex file.

**Comment by galex** [comment]
It is indeed a big module (android app which depends on many other modules and external dependencies) but it is "normal" for android apps to go over that limit, that's why we [enable multiDex](https://developer.android.com/studio/build/multidex.html). 

Do you mean this is a buck limitation and there is no way going around it?

Does[ this issue](https://github.com/facebook/buck/issues/309) mean multidex is not supported for apps which have minSDK=21 (or more), thus not using the multidex support library?

**Comment by runningcode** [comment]
So, Buck has multidex support and you can continue to use the multidex library.
However, in order for Buck to work, you will have to split up your module so that the module itself has less than 65k methods without including dependencies of that module.

**Comment by galex** [comment]
Understood, thank you for the explanation!
