### ISSUE TITLE
No such file or directory: '/Users/ian/.gradle/caches/okbuck/buck/build/buck-info.json'

### ISSUE THREAD

**Issue by ianchild** [uber/okbuck#606]
2018-03-21 14:00:20,289 [ERROR][buck.py:157] [Errno 2] No such file or directory: '/Users/ian/.gradle/caches/okbuck/buck/build/buck-info.json'
Traceback (most recent call last):
  File "/Users/ian/.gradle/caches/okbuck/buck/bin/../programs/buck.py", line 131, in <module>
    exit_code = main(sys.argv, reporter)
  File "/Users/ian/.gradle/caches/okbuck/buck/bin/../programs/buck.py", line 112, in main
    with get_repo(project) as buck_repo:
  File "/Users/ian/.gradle/caches/okbuck/buck/bin/../programs/buck.py", line 97, in get_repo
    return BuckRepo(THIS_DIR, p, reporter)
  File "/Users/ian/.gradle/caches/okbuck/buck/programs/buck_repo.py", line 46, in __init__
    super(BuckRepo, self).__init__(buck_project, buck_reporter)
  File "/Users/ian/.gradle/caches/okbuck/buck/programs/buck_tool.py", line 170, in __init__
    self._package_info = self._get_package_info()
  File "/Users/ian/.gradle/caches/okbuck/buck/programs/buck_repo.py", line 65, in _get_package_info
    return json.loads(self.__read_file(BUCK_INFO_LOCATION))
  File "/Users/ian/.gradle/caches/okbuck/buck/programs/buck_repo.py", line 68, in __read_file
    with open(os.path.join(self.buck_dir, filename)) as file:
IOError: [Errno 2] No such file or directory: '/Users/ian/.gradle/caches/okbuck/buck/build/buck-info.json'

**Comment by kageiit** [comment]
Please use latest okbuck and update your buck wrapper with `./gradlew :buckWrapper`. We do not use buck built from source anymore
