### ISSUE TITLE
Add support for jetifier

### ISSUE THREAD

**Issue by kageiit** [uber/okbuck#653]
https://developer.android.com/topic/libraries/support-library/androidx-rn

Waiting for a final release

**Comment by artem-zinnatullin** [comment]
Given that OkBuck now delegates to Buck to download dependencies, should we integrate Jetifier into Buck itself or should it be dependency postprocessing step generated by OkBuck?

**Comment by alexjlockwood** [comment]
FYI, Android X just went stable on Monday (9/21/2018).

**Comment by hzsweers** [comment]
What's the source on cli usage? AFAIK the only guarantee they've ever made was to just give a gigantic list of all the mappings

**Comment by kageiit** [comment]
We are talking to the frameworks team directly about the docs

**Comment by kageiit** [comment]
CLI instructions are out: https://developer.android.com/studio/command-line/jetifier

@thalescm wanna try tackling this?

**Comment by kageiit** [comment]
We would want to depend on the jetifier artifact from maven.google.com and create a java_binary with an isolated configuration in okbuck (similar to what we do with lint etc.). Then we can create genrules to process prebuilt aars/jars with the tool before consumption as long as said jar/aar has a dependency on a support library (info available during resolution in okbuck)

**Comment by jbarr21** [comment]
it seems that JARs are not getting jetified ([only enabled for AARs](https://github.com/uber/okbuck/blob/9046980741fd75319eef4f4ee251c5732b057f56/buildSrc/src/main/rocker/com/uber/okbuck/template/config/BuckDefs.rocker.raw#L319)?). i noticed that stylist and lumber still had dependencies on `android.support.annotations`

**Comment by TonyTangAndroid** [comment]
I am trying to integrate okbuck into a comparatively complicated [project](https://github.com/TonyTangAndroid/android-base/tree/dev_buck) to get my hands dirty with okbuck. And I am running exception when command is executed `./buckw install //app:bin_debug --run` with the follow exception. I would say that I am running the same issue with this [one](https://stackoverflow.com/q/54345390/4068957) from stackoverflow. Any advice in resolving this problem?


> Exception in thread "main" java.lang.IllegalArgumentException: The given artifact contains a string literal with a package reference 'android.support.design.widget' that cannot be safely rewritten. Libraries using reflection such as annotation processors need to be updated manually to add support for androidx.
        at com.android.tools.build.jetifier.processor.transform.bytecode.CoreRemapperImpl.rewriteString(CoreRemapperImpl.kt:91)
        at com.android.tools.build.jetifier.processor.transform.bytecode.asm.CustomRemapper.mapValue(CustomRemapper.kt:75)
        at org.objectweb.asm.commons.ClassRemapper.visitField(ClassRemapper.java:113)
        at org.objectweb.asm.ClassReader.readField(ClassReader.java:883)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:694)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.android.tools.build.jetifier.processor.transform.bytecode.ByteCodeTransformer.runTransform(ByteCodeTransformer.kt:39)
        at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:366)
        at com.android.tools.build.jetifier.processor.archive.ArchiveFile.accept(ArchiveFile.kt:41)
        at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:348)
        at com.android.tools.build.jetifier.processor.archive.Archive.accept(Archive.kt:70)
        at com.android.tools.build.jetifier.processor.Processor.transformLibrary(Processor.kt:344)
        at com.android.tools.build.jetifier.processor.Processor.transform(Processor.kt:207)
        at com.android.tools.build.jetifier.processor.Processor.transform$default(Processor.kt:194)
        at com.android.tools.build.jetifier.standalone.Main.run(Main.kt:147)
        at com.android.tools.build.jetifier.standalone.Main$Companion.main(Main.kt:101)
        at com.android.tools.build.jetifier.standalone.Main.main(Main.kt)

**Comment by TonyTangAndroid** [comment]
I have resolved this issue by adding a jetifier block in root level build.gradle.  Please refer to the pull request [here]( https://github.com/TonyTangAndroid/HelloBuck/pull/6/files) that has fixed the AndroidX issue.

This is the whole code block related to okbuck.

```
okbuck {
    buildToolVersion = '28.0.3'

    lint {
        disabled = true
    }
    externalDependencies {
        downloadInBuck = false
    }
    jetifier {
        aarOnly = true
    }
}
```

**Comment by thalescm** [comment]
@TonyTangAndroid If you put the value of `aarOnly` to false the issue arises again or still appears as fixed?

**Comment by TonyTangAndroid** [comment]
If I set `aarOnly = false`, it will NOT work. If I set `aarOnly = true`, it will work.  This issue could be stably reproduced by toggling this flag.

**Comment by thalescm** [comment]
Ok, tks. It's just that if setting to false would continue to not fail, the issue would be on okbuck. But as you described, it's not.
