### ISSUE TITLE
java.lang.IllegalArgumentException: Self-suppression not permitted

### ISSUE THREAD

**Issue by kxfang** [uber/okbuck#755]
When running our build the other day I ran into this error randomly. It went away after I cleaned and reran okbuck, but thought it was strange that this happened at all.

```
Buck encountered an internal error
java.lang.IllegalArgumentException: Self-suppression not permitted
    at java.lang.Throwable.addSuppressed(Throwable.java:1043)
    at com.facebook.buck.core.rulekey.calculator.ParallelRuleKeyCalculator.lambda$calculate$1(ParallelRuleKeyCalculator.java:103)
    ... 13 more
Caused by: com.facebook.buck.util.exceptions.BuckUncheckedExecutionException: When amending binaryJar.: com.facebook.buck.util.exceptions.BuckUncheckedExecutionException: When adding binaryJar with value /Users/kfang/src/instant-android/.okbuck/workspace/lint/lint-dummy.jar: java.nio.file.NoSuchFileException: /Users/kfang/src/instant-android/.okbuck/workspace/lint/lint-dummy.jar
    at com.facebook.buck.rules.keys.DefaultAlterRuleKey.amendKey(DefaultAlterRuleKey.java:34)
    at com.facebook.buck.rules.keys.AlterRuleKeys.amendKey(AlterRuleKeys.java:60)
    at com.facebook.buck.rules.keys.AlterRuleKeys.amendKey(AlterRuleKeys.java:37)
    at com.facebook.buck.rules.keys.RuleKeyFieldLoader.setFields(RuleKeyFieldLoader.java:66)
    at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.newPopulatedBuilder(DefaultRuleKeyFactory.java:97)
    at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.lambda$build$0(DefaultRuleKeyFactory.java:125)
    at com.facebook.buck.rules.keys.DefaultRuleKeyCache.calculateNode(DefaultRuleKeyCache.java:72)
    at com.facebook.buck.rules.keys.DefaultRuleKeyCache.lambda$null$2(DefaultRuleKeyCache.java:111)
    at com.facebook.buck.util.function.ThrowingSupplier.lambda$fromSupplier$1(ThrowingSupplier.java:41)
    at com.facebook.buck.util.AbstractMemoizer.get(AbstractMemoizer.java:42)
    at com.facebook.buck.util.Memoizer.get(Memoizer.java:27)
    at com.facebook.buck.util.Memoizer.get(Memoizer.java:30)
    at com.facebook.buck.util.MoreSuppliers$MemoizingSupplier.get(MoreSuppliers.java:76)
    at com.facebook.buck.rules.keys.DefaultRuleKeyCache.getNode(DefaultRuleKeyCache.java:119)
    at com.facebook.buck.rules.keys.DefaultRuleKeyCache.get(DefaultRuleKeyCache.java:140)
    at com.facebook.buck.rules.keys.TrackedRuleKeyCache.get(TrackedRuleKeyCache.java:52)
    at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.build(DefaultRuleKeyFactory.java:122)
    at com.facebook.buck.rules.keys.DefaultRuleKeyFactory.build(DefaultRuleKeyFactory.java:41)
    at com.facebook.buck.core.rulekey.calculator.ParallelRuleKeyCalculator.lambda$calculate$1(ParallelRuleKeyCalculator.java:102)
    ... 13 more
Caused by: com.facebook.buck.util.exceptions.BuckUncheckedExecutionException: When adding binaryJar with value /Users/kfang/src/instant-android/.okbuck/workspace/lint/lint-dummy.jar: java.nio.file.NoSuchFileException: /Users/kfang/src/instant-android/.okbuck/workspace/lint/lint-dummy.jar
    at com.facebook.buck.rules.keys.AbstractRuleKeyBuilder.setReflectively(AbstractRuleKeyBuilder.java:57)
    at com.facebook.buck.rules.keys.AbstractRuleKeyBuilder.setReflectively(AbstractRuleKeyBuilder.java:42)
    at com.facebook.buck.rules.keys.DefaultAlterRuleKey.amendKey(DefaultAlterRuleKey.java:32)
    ... 31 more
Caused by: java.nio.file.NoSuchFileException: /Users/kfang/src/instant-android/.okbuck/workspace/lint/lint-dummy.jar
    at com.facebook.buck.util.cache.impl.StackedFileHashCache.lambda$get$0(StackedFileHashCache.java:199)
    at java.util.Optional.orElseThrow(Optional.java:290)
    at com.facebook.buck.util.cache.impl.StackedFileHashCache.get(StackedFileHashCache.java:199)
    at com.facebook.buck.rules.keys.RuleKeyBuilder.setPath(RuleKeyBuilder.java:231)
    at com.facebook.buck.rules.keys.RuleKeyBuilder.setSourcePathDirectly(RuleKeyBuilder.java:180)
    at com.facebook.buck.rules.keys.DefaultRuleKeyFactory$Builder.setSourcePath(DefaultRuleKeyFactory.java:198)
    at com.facebook.buck.rules.keys.DefaultRuleKeyFactory$Builder.setSourcePath(DefaultRuleKeyFactory.java:165)
    at com.facebook.buck.rules.keys.AbstractRuleKeyBuilder.setReflectively(AbstractRuleKeyBuilder.java:162)
    at
    ... 33 more

    When computing rulekey for //.okbuck/workspace/lint:lint-dummy.jar
```

**Comment by artem-zinnatullin** [comment]
Yeah, I specifically asked if `.okbuck` was deleted prior or while Buck was running, but @kxfang said no

Also, watchman is in place (buckw would detect the change)

Not sure how such state is possible 🤔
