### ISSUE TITLE
NullPointerException when running ./buckw targets

### ISSUE THREAD

**Issue by matthewrkula** [uber/okbuck#820]
I'm trying to use `okbuck` v0.47.0 but this error is preventing me from doing so. It looks similar to #690 but the null pointer is happening in `com.android.build.gradle.internal.api.BaseVariantImpl` not in this library itself which I've traced to [here](https://android.googlesource.com/platform/tools/base/+/studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/api/BaseVariantImpl.java?autodive=0%2F%2F#469)

Any idea what might be causing this? I followed the steps to set up just fine.

```
Caused by: java.lang.NullPointerException
        at com.android.build.gradle.internal.api.BaseVariantImpl.getNdkCompile(BaseVariantImpl.java:469)
        at com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated.getNdkCompile(Unknown Source)
        at com.uber.okbuck.core.model.android.AndroidAppTarget.<init>(AndroidAppTarget.java:50)
        at com.uber.okbuck.core.model.android.AndroidAppTarget.<init>(AndroidAppTarget.java:86)
        at com.uber.okbuck.core.model.base.TargetCache.lambda$getTargets$0(TargetCache.java:39)
        at com.google.common.collect.CollectCollectors.lambda$toImmutableMap$1(CollectCollectors.java:61)
        at com.uber.okbuck.core.model.base.TargetCache.getTargets(TargetCache.java:37)
        at com.uber.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.java:72)
        at com.uber.okbuck.generator.BuckFileGenerator.generate(BuckFileGenerator.java:50)
        at com.uber.okbuck.OkBuckGradlePlugin.lambda$apply$7(OkBuckGradlePlugin.java:310)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:672)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$4.run(ExecuteActionsTaskExecuter.java:338)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
```

**Comment by kageiit** [comment]
Which version of android gradle plugin are you on? Okbuck supports upto max 3.2.0 only at the moment

**Comment by LNeway** [comment]
I have the same issue and my gradle plugin version is 3.1.3

the following is the exception log 
`Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
        at com.uber.okbuck.core.dependency.DependencyCache.build(DependencyCache.java:182)
        at com.uber.okbuck.core.dependency.DependencyCache.<init>(DependencyCache.java:47)
        at com.uber.okbuck.core.dependency.DependencyCache.<init>(DependencyCache.java:57)
        at com.uber.okbuck.OkBuckGradlePlugin.lambda$apply$5(OkBuckGradlePlugin.java:272)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:786)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:753)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 33 more`

**Comment by kageiit** [comment]
This should not longer be an issue with the latest okbuck. Please re-open if it happens on latest
