### ISSUE TITLE
OKBuck is failling with akamai lib (Working fine with studio)

### ISSUE THREAD

**Issue by lavekush-t** [uber/okbuck#885]
1. Studio version = 3.5.1
2. buck version = 0.41.1
3. gradleWrapper version = 5.4.1

```
Building... 3.8 sec (99%) 861/863 jobs, 0 updated
 - //customerapp:bin_liveDevDebug#d8,dex_merge... 0.8 sec (running smart_dex[0.7 sec])
 - IDLE
 - IDLE
 - IDLE
 - IDLE
 - IDLE
 - IDLE
 - IDLE
 - IDLE
 - 3 MORE THREADS: [ ] [ ] [ ]
Error: Program type already present: com.akamai.botman.CYFMonitor
com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:65)
        at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
        at com.android.tools.r8.D8.run(D8.java:73)
        at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:306)
        at com.facebook.buck.android.DxStep.execute(DxStep.java:268)
        at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
        at com.facebook.buck.android.SmartDexingStep.lambda$null$1(SmartDexingStep.java:236)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:127)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: com.akamai.botman.CYFMonitor
        at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:116)
        at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:74)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:59)
        ... 12 more

```

**Comment by kageiit** [comment]
This is not an okbuck failure. Its a failure in buck build. This usually means you have two jars/aars that define `com.akamai.botman.CYFMonitor`. Try to look for `CYFMonitor` in `buck-out/**/*.txt` to find the culprits for the duplicates

**Comment by ignindra** [comment]
@lavekush-t, as a temporary solution, you can also delete either the `jar` or `aar` that you don't need manually, by replacing it in all of generated `BUCK` file (`BUCK` is the name of the file) when the error occurs.
If you're using any kind of IDE/text editor with file filtering functionality, you could also use that to find and replace all of the unneeded jars/aars all at once.

Apparently the error happen because the suspected library generate _both_ `aar` and `jar`
